### PR TITLE
Documentation around new SAML TIB Provider

### PR DESCRIPTION
**Pull request by joshblakeley**
See related TIB PR here:

https://github.com/TykTechnologies/tyk-identity-broker/pull/103

To merge when TIB release with that PR is released.

### CODE REVIEW

**Review by marksou — APPROVED** [review]
👍

**Comment by joshblakeley** [comment]
This is out for tib so merge please @marksou

**Comment by sredxny** [comment]
I just made a slight update regarding certificate for saml, and now this is ready to go live

**Comment by marksou** [comment]
Note that I'm going to merge this into the `new_design` branch, which will be merged into master early next week

**Comment by joshblakeley** [comment]
Thanks Mark

**Pull request merged**
