### PR TITLE
[DX-1324] Menu Collapse

### PR DESCRIPTION
**Pull request by fredoyetayo**
### **User description**
<br>

---

### Preview Link

https://deploy-preview-4633--tyk-docs.netlify.app/docs/nightly/apim/

<br>

### Description

Implementation to reduce the clickable areas and modify the tree view plugin. This implementation fixes the bug and allows a user easily navigate the table of content.
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

### **PR Type**
enhancement

___

### **Description**
- Enhanced side menu styling in SCSS by adjusting padding and cursor properties.
- Improved JavaScript event handling to prevent menu toggle when clicking on links.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>_side-menu.scss</strong><dd><code>Enhancements to Side Menu Styling and Interaction</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_side-menu.scss
<li>Commented out <code>margin-bottom</code> and added <code>padding-bottom</code> for better <br>spacing.<br> <li> Added <code>cursor: pointer</code> to improve user interaction cues.<br> <li> Enhanced link styles within the menu for better visibility and <br>interaction.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4633/files#diff-ec2a82dc0661a7f9d0f574a4b599afbe4ff53f179b52e683311c41643b6aed72">+21/-1</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>simpletree.min.js</strong><dd><code>Improve Event Handling in Treeview Menu</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/static/js/simpletree.min.js
<li>Modified event handling to prevent toggling when clicking on links.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4633/files#diff-6014eb0715db52ae3b1f0274503926b72081c4420644f103a663fbc82a714eed">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by yurisasuke** [comment]
@fredoyetayo   The new Menu Items are too squeezed. (The previous one were more spaced looked better)


Screenshot 2024-05-16 at 08 53 56

**Comment by fredoyetayo** [comment]
Thank you for the feedback @Keithwachira - I'll increase the padding.

**Comment by yurisasuke** [comment]
@fredoyetayo  the issue seems to still be happening when I click between **operation and Bau**  and  **Featured Guide** (At the lower bottom of operation and Bau that is  where i have draw a rectangle)
Screenshot 2024-05-17 at 22 58 54

**Review by yurisasuke — APPROVED** [review]

**Pull request merged**
