### PR TITLE
[DX-1253]reduce the padding with content

### PR DESCRIPTION
**Pull request by yurisasuke**
https://deploy-preview-4404--tyk-docs.netlify.app/docs/nightly/troubleshooting/tyk-pump/pump-overloaded/

https://deploy-preview-4404--tyk-docs.netlify.app/docs/nightly/tyk-stack/

[DX-1253]

[DX-1253]: https://tyktech.atlassian.net/browse/DX-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by letzya — CHANGES_REQUESTED** [review]
The space of the heading from the text below is still not close enough
https://deploy-preview-4404--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/release-notes/version-5.3/#tyk-oas-apis-compatibility-caveats---tyk-oss

https://deploy-preview-4404--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/release-notes/version-5.3/#tyk-oas-feature-maturity

Please reduce it

**Comment by yurisasuke** [comment]
> The space of the heading from the text below is still not close enough https://deploy-preview-4404--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/release-notes/version-5.3/#tyk-oas-apis-compatibility-caveats---tyk-oss
> 
> https://deploy-preview-4404--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/release-notes/version-5.3/#tyk-oas-feature-maturity
> 
> Please reduce it

@letzya  Fixed

**Pull request merged**
