### PR TITLE
[DX-769] Refactor plugins based on customer feedback

### PR DESCRIPTION
**Pull request by dcs3spp**
[DX-769](https://tyktech.atlassian.net/browse/DX-769)

 Refactor plugins based on customer feedback.
- [Add Tyk Cloud Platform Resources To GoLang Plugins](https://deploy-preview-3521--tyk-docs.netlify.app/docs/nightly/plugins/supported-languages/golang)
- [Update ordering of Using Plugins menu item](https://deploy-preview-3521--tyk-docs.netlify.app/docs/nightly/tyk-cloud/using-plugins/)

[DX-769]: https://tyktech.atlassian.net/browse/DX-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rewsmith — CHANGES_REQUESTED** [review]
Hi @dcs3spp The changes to the 2 files currently on the PR are both good to go.  I mentioned on the associated Jira that the list on [Using Plugins](https://tyk.io/docs/tyk-cloud/using-plugins/) should be updated to match the new menu order, so can we make that change as well?  Sorry if that wasn't clear.

**Comment by dcs3spp** [comment]
Thanks @rewsmith, I have updated so that see also section reflects using plugins menu ordering. Would you be to review again?

**Review by rewsmith — APPROVED** [review]
LGTM

**Pull request merged**
