### PR TITLE
[DX-474]Hide red lines in production that have empty pages.

### PR DESCRIPTION
**Pull request by yurisasuke**
### For internal users - please add a Jira DX PR ticket to the subject!
DX-474
---
### Preview Link

https://deploy-preview-2925--tyk-docs.netlify.app/docs/nightly/apim/

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
lgtm

**Comment by letzya** [comment]
@Keithwachira we also need to hide the orphan tab, can we do it in this pr?

**Review by letzya — CHANGES_REQUESTED** [review]
hide orphan :)

**Comment by yurisasuke** [comment]
> @Keithwachira we also need to hide the orphan tab, can we do it in this pr?

I was thinking for ophans we can do it in the menu.yaml

**Comment by letzya** [comment]
@Keithwachira so are you adding it to this pr?

**Comment by yurisasuke** [comment]
> @Keithwachira so are you adding it to this pr?

Yes . I have added it.

**Review by letzya — APPROVED** [review]

**Pull request merged**
