### PR TITLE
[DX-1235]UI fixes- DX 1235

### PR DESCRIPTION
**Pull request by fredoyetayo**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[DX-1235]

---

### Preview Link

https://deploy-preview-4394--tyk-docs.netlify.app/docs/nightly

<br>

### Description
UI fixes to h2 and h3 titles/heading and Action Bottom container - DX 1235

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

## **Type**
enhancement

___

## **Description**
- Adjusted the top margin of `h3` headings to 20px for better spacing in the content.
- Introduced dynamic padding for `h2` and `h3` headings, making the spacing more responsive.
- Updated the `.action_bottom` container to have dynamic margins, improving the visual flow of the page.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>_bespoke.scss</strong><dd><code>Reduce Top Margin for h3 Headings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_bespoke.scss
- Adjusted the top margin of `h3` headings from 40px to 20px.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4394/files#diff-4d88d302558832943d8a99db09e36c42f8f75ba4a04df83b0b2ada3e1613e4a5">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_docs.scss</strong><dd><code>Dynamic Padding for h2 and h3 Headings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_docs.scss
<li>Changed the padding-top for <code>h2</code> headings from a fixed pixel value to <br>2%.<br> <li> Modified the padding-top for <code>h3</code> headings from a fixed pixel value to <br>1%.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4394/files#diff-d29767519ca2fa4d8fce78b76e949905e03684c9f9d6572ff6b4f23888480e7e">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_structure.scss</strong><dd><code>Dynamic Margin Adjustment for Action Bottom Container</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_structure.scss
<li>Updated the <code>.action_bottom</code> container to have dynamic top and bottom <br>margins set to 2%.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4394/files#diff-9351f90fa51c1ad933900122d614f50cee937500d4e7ed8a7b4b6ce1f49d3bd3">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

[DX-1235]: https://tyktech.atlassian.net/browse/DX-1235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by letzya** [comment]
image

**Review by yurisasuke — APPROVED** [review]

**Pull request merged**
