### PR TITLE
[DX-119] Adding reading time and move last updated to the top

### PR DESCRIPTION
**Pull request by letzya**
### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-119

https://deploy-preview-3531--tyk-docs.netlify.app/docs/nightly/apim-best-practice/overview/

<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Comment by letzya** [comment]
@Keithwachira 
1. could you please help me with CSS - make it a small font?
2. remove from homepage

**Comment by letzya** [comment]
@Keithwachira

**Comment by letzya** [comment]
@Keithwachira

**Comment by yurisasuke** [comment]
> @Keithwachira

@letzya i have reduced the font and removed time from the homepage.

**Review by yurisasuke — APPROVED** [review]

**Pull request merged**
