### PR TITLE
Istio Ingress Guide

### PR DESCRIPTION
**Pull request by joshblakeley**
Step by step guide to deploying Tyk as the Ingress Gateway for an Istio Service Mesh including deploying APIs using Tyk Operator.

Relies on https://github.com/TykTechnologies/tyk-helm-chart/pull/80

and

https://github.com/TykTechnologies/tyk-operator/pull/261

EDIT:

Both the helm chart changes and operator changes are available to the public so this doc is ready to go.

### CODE REVIEW

**Comment by joshblakeley** [comment]
@marksou This guide is ready to go into the docs when possible. Thanks!

**Review by marksou — CHANGES_REQUESTED** [review]
Hi @joshblakeley I've noticed there is no Front Matter for this page, so it won't appear in the menu anywhere. Can you fix?

**Comment by joshblakeley** [comment]
> Hi @joshblakeley I've noticed there is no Front Matter for this page, so it won't appear in the menu anywhere. Can you fix?

I have not got a clue what that means - would appreciate a pointer or three :)

**Comment by marksou** [comment]
@joshblakeley https://github.com/TykTechnologies/tyk-docs#front-matter. We're up to our armpits with the restructure merge, so I'll be back in touch after that has settled down and we can put it in the right place.

**Review by marksou — APPROVED** [review]
👍

**Pull request merged**
