### PR TITLE
[DX-1173] Highlight new default timeout introduced in 5.2.2

### PR DESCRIPTION
**Pull request by andyo-tyk**
### Description
Clarified the introduction of a new default proxy timeout in 5.2.2 - tagged this in the breaking changes section because (whilst it's a bug fix rather than a breaking change per-se) it can have unexpected impact on users relying on the previous behaviour.

___

## **Type**
enhancement, documentation

___

## **Description**
- Introduced a new default proxy timeout of 30 seconds for upstream requests to address a bug where request timeouts were not correctly enforced. This change is documented under the "Default proxy timeout" subsection for the release date 31 Oct 2023.
- Updated the "Breaking Changes" section across various release dates for clarity and consistency.
- Added detailed documentation on the enforced timeout fix and how to alter the default timeout using `proxy_default_timeout`.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>version-5.2.md</strong><dd><code>Highlighting New Default Proxy Timeout and Clarifying Breaking Changes</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
<li>Clarified the "Breaking Changes" section across multiple release <br>dates.<br> <li> Introduced a new default proxy timeout of 30 seconds for upstream <br>requests.<br> <li> Documented the fix for enforced timeouts on a per-request basis and <br>how to alter the default timeout.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4240/files#diff-b6aafe51c3462aa4b79bcc868277e2224ec67ccd562a24716ddcae0401cda8bc">+11/-9</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by andyo-tyk** [comment]
@dcs3spp I attempted to link to an anchor ({#enforced-timeout-fix}) that I added in the page (as we do with the separate release note sections) but it doesn't appear to have worked. Is there a way to do this? If not then we'll have to remove it.

**Review by OldStubbsy — APPROVED** [review]
Looks good to me

**Review by dcs3spp — APPROVED** [review]
PR LGTM, will merge and release

**Pull request merged**
