### PR TITLE
Clarifying Language for Custom Domains

### PR DESCRIPTION
**Pull request by nerdydread**
Added clarifying language to custom domains and edge gateways.

### CODE REVIEW

**Comment by marksou** [comment]
@nerdydread Who is best to review this from a technical viewpoint?

**Review by excieve — COMMENTED** [review]
Thanks @nerdydread! This is the case for both the Edges and the Control Planes and between them too. In other words, a custom domain must be unique for any deployment.

**Review by craigtyk — APPROVED** [review]
lgtm

**Pull request merged**
