### PR TITLE
[DX-1399] Update tyk-pump-dashboard-config.md

### PR DESCRIPTION
**Pull request by carolwkc**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

https://tyktech.atlassian.net/browse/DX-1399

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

___

### **PR Type**
documentation

___

### **Description**
- Removed the instruction to set `use_sharded_analytics: true` in the Dashboard config when `use_mixed_collection: true` is set in the pump.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tyk-pump-dashboard-config.md</strong><dd><code>Remove `use_sharded_analytics` setting instruction from documentation</code></dd></summary>
<hr>

tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
<li>Removed the instruction to set <code>use_sharded_analytics: true</code> in the <br>Dashboard config when <code>use_mixed_collection: true</code> is set in the pump.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4728/files#diff-f74fb26f91f5d842017aa0433ea6e7291060cc2008e05648fd904892c07076eb">+0/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by mativm02 — APPROVED** [review]

**Comment by dcs3spp** [comment]
@caroltyk Can you add label(s) indicating what release this targets, e.g 5.4.0 or now (5.3)?

**Review by dcs3spp — DISMISSED** [review]
PR LGTM, @caroltyk can you add a label indicating which release this targets, e.g. is it now or scheduled for Tyk Pump 1.1.0 (5.4.0)?

**Comment by letzya** [comment]
Changed to draft till we know when it's needed to be released. I think it's now as far as I understand it but please confirm

**Pull request merged**
