### PR TITLE
[DX-955] Added a direct link to the upgrade section

### PR DESCRIPTION
**Pull request by letzya**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

https://deploy-preview-3890--tyk-docs.netlify.app/docs/product-stack/tyk-gateway/release-notes/version-5.2/#upgrade-instructions
https://deploy-preview-3890--tyk-docs.netlify.app/docs/product-stack/tyk-dashboard/release-notes/version-5.2/#upgrade-instructions

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
PR LGTM

**Comment by dcs3spp** [comment]
@letzja I approved and merged but when merging to release-5.2 the PR was in draft status 
https://github.com/TykTechnologies/tyk-docs/pull/3900

Might be better to create separate PRs
1. PR for Template Update merge into master
2. PR with Release notes 5.2 and 5.1 upgrade links added

**Comment by letzya** [comment]
I did not understand why it happened but could you please sort it? Thanks

**Pull request merged**
