### PR TITLE
[DX-611]change footer color to black

### PR DESCRIPTION
**Pull request by yurisasuke**
### For internal users - please add a Jira DX PR ticket to the subject!
DX-611
---
### Preview Link
https://deploy-preview-3094--tyk-docs.netlify.app/docs/nightly/
### Should look like
Screenshot 2023-08-08 at 12 51 41

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
lgtm

**Comment by dcs3spp** [comment]
@keith once the rebranding is complete, then maybe add a ticket to remove the unused colour scheme?

**Comment by yurisasuke** [comment]
> @keith once the rebranding is complete, then maybe add a ticket to remove the unused colour scheme?

yes let me actually create it right now to make sure i don't forget

**Pull request merged**
