### PR TITLE
[DX-1452] Delete docs for a deprecated product

### PR DESCRIPTION
**Pull request by letzya**
### For internal users - Please add a Jira DX PR ticket to the subject!
<be>

Remove docs for deprecated product offering 
https://tyk.io/docs/advanced-configuration/manage-multiple-environments/with-tyk-cloud-classic
https://tyk.io/docs/frequently-asked-questions/cloud-classic-virtual-endpoints-not-working

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

___

### **PR Type**
Documentation

___

### **Description**
- Removed documentation related to Tyk Cloud Classic, including:
  - Guide on managing multiple environments with Tyk Cloud Classic.
  - FAQ on Cloud Classic Virtual Endpoints not working.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>with-tyk-cloud-classic.md</strong><dd><code>Delete documentation for managing multiple environments with Tyk Cloud </code><br><code>Classic.</code></dd></summary>
<hr>

tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-cloud-classic.md
<li>Removed the entire document related to managing multiple environments <br>with Tyk Cloud Classic.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4866/files#diff-8616a9330463c87056194b163817728b7d746bf2ab3b1aa966d6bb92432b9e41">+0/-13</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>cloud-classic-virtual-endpoints-not-working.md</strong><dd><code>Delete FAQ document about Cloud Classic Virtual Endpoints issues.</code></dd></summary>
<hr>

tyk-docs/content/frequently-asked-questions/cloud-classic-virtual-endpoints-not-working.md
<li>Removed the entire FAQ document about Cloud Classic Virtual Endpoints <br>not working.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4866/files#diff-a73ba5ef7930cb71a8da695259a3e69f09fbcd6bf42745db5c4067cc9becb4d9">+0/-13</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by letzya** [comment]
@Keithwachira what do you think?

**Comment by yurisasuke** [comment]
> @Keithwachira what do you think?

@letzya It would be nice to also add aliases in this pull request so that if this links have been referenced externally/internally we can direct the traffic to another page in the docs

**Comment by letzya** [comment]
closing. might do something else

**Comment by letzya** [comment]
@Keithwachira which link do you think will be suitable for these pages (bear in mind that internal links should not have these pages as the ci would have failed)

**Pull request closed without merging**
