### PR TITLE
TT-5804 Update ES supported versions

### PR DESCRIPTION
**Pull request by carolwkc**
### For internal users - please add a Jira DX PR ticket to the subject!
---
### Description

Update ElasticSearch supported version since we don’t support elasticsearch 8.0+

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
lgtm, will merge and release once peer review approved

**Comment by dcs3spp** [comment]
@caroltyk Can you please add label for which release this is targeted

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Pull request merged**
