### PR TITLE
[DX-1110] Update synchroniser.md

### PR DESCRIPTION
**Pull request by Yubee116**
## **User description**
Control Plane configuration" refers to a "Controller Gateway", yet the provided code snippet suggests a Worker Gateway configuration with slave_options. This might lead to confusion.

This PR removes the slave_options config and leaves hash_keys which is relevant to the context of that section

<br>
---

### Preview Link
https://deploy-preview-4160--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser/#configuring-the-synchroniser-for-tyk-self-managed
<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

## **Type**
documentation

___

## **Description**
- Removed the `slave_options` configuration from the Controller Gateway section to prevent confusion between Controller and Worker Gateway configurations.
- Ensured the `hash_keys` configuration remains in the document, as it is relevant to the section's context.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>synchroniser.md</strong><dd><code>Clarification and Simplification of Gateway Configuration</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser.md
<li>Removed the <code>slave_options</code> configuration from the Controller Gateway <br>section to avoid confusion.<br> <li> Retained the <code>hash_keys</code> configuration as relevant to the section <br>context.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4160/files#diff-f1713746a7eae517a35a826b3e6be53378ba3097e14d69bcd3e337530e744669">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by OldStubbsy — APPROVED** [review]
Tested that having `"slave_options":{ "synchroniser_enabled": true }` in the control plane gateway is not necessary

**Review by dcs3spp — APPROVED** [review]
Thanks Pete, PR LGTM

**Pull request merged**
