### PR TITLE
Update bitnami/redis installation instruction

### PR DESCRIPTION
**Pull request by carolwkc**
### For internal users - please add a Jira DX PR ticket to the subject!
---
### Description

Hey team, our instructions for installing Redis in our [documentation linked here](https://tyk.io/docs/tyk-self-managed/tyk-helm-chart/#redis) actually installs a non-complaint version of Tyk
helm install tyk-redis bitnami/redis -n tyk
installs this version of redis
[docker.io/bitnami/redis:7.0.12-debian-11-r2](http://docker.io/bitnami/redis:7.0.12-debian-11-r2)

As a fix, we should add a fixed image tag
e.g. `helm install tyk-redis bitnami/redis -n tyk --set image.tag=6.2.13`

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Comment by dcs3spp** [comment]
@caroltyk Can you add a label for which release version targeted for? I can approve but not yet merge until new website nav issues have been addressed and merged into release 5.1

**Review by letzya — APPROVED** [review]

**Comment by letzya** [comment]
@caroltyk I added the label `now` to the PR so we know it's for now

**Pull request merged**
