### PR TITLE
add documentation for CORS default values

### PR DESCRIPTION
**Pull request by pvormste**
Related to https://github.com/TykTechnologies/tyk-analytics/issues/2056

### CODE REVIEW

**Review by lghiur — APPROVED** [review]

**Review by jay-deshmukh — APPROVED** [review]

**Comment by pvormste** [comment]
Needs a new page for troubleshooting - changing to draft

**Comment by lghiur** [comment]
@pvormste this is great, thanks for documenting it!

**Review by jay-deshmukh — APPROVED** [review]
LGTM

**Review by marksou — APPROVED** [review]
👍

**Pull request merged**
