### PR TITLE
[DX-724]add tags to  bottom of page get them indexed

### PR DESCRIPTION
**Pull request by yurisasuke**
### For internal users - please add a Jira DX PR ticket to the subject
DX-724
---
### Preview Link
https://deploy-preview-3307--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/newrelic/

https://deploy-preview-3307--tyk-docs.netlify.app/docs/nightly/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware/

### Description
This will help with seo as this will get indexed

### CODE REVIEW

**Comment by letzya** [comment]
@Keithwachira can we please see what it looks like when it's at the right corner, above "on this page" , where it's more visible? maybe also add "tags:"

**Comment by yurisasuke** [comment]
> @Keithwachira can we please see what it looks like when it's at the right corner, above "on this page" , where it's more visible? maybe also add "tags:"

Let me create another Pr with the tags at the right corner.

**Comment by yurisasuke** [comment]
> @Keithwachira can we please see what it looks like when it's at the right corner, above "on this page" , where it's more visible? maybe also add "tags:"

@letzya  here is a sample of the tags on the right :https://github.com/TykTechnologies/tyk-docs/pull/3310

**Comment by letzya** [comment]
> #3310

Yes I saw it and thought it's better if we show it in a single row, not a list (but it might look like a list due to the limited space). Regardless we agreed that Jevan will help us, right?

**Comment by yurisasuke** [comment]
Parked for now .

**Pull request closed without merging**
