### PR TITLE
[DX-990] Update mdcb-config.md

### PR DESCRIPTION
**Pull request by buraksekili**
Fix typo in environment variable annotation of  `security.private_certificate_encoding_secret` config.

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — COMMENTED** [review]
Hi @buraksekili Is the typo in the configuration variable in use in a release? Or is the typo  in the content file only?

**Comment by buraksekili** [comment]
hi @dcs3spp, there is a typo in the content file only but it would be great to confirm with MDCB team.

**Comment by dcs3spp** [comment]
> hi @dcs3spp, there is a typo in the content file only but it would be great to confirm with MDCB team.

@caroltyk for the MDCB environment variable typo fix in this PR, is it a typo in the source code also or just the docs?

**Comment by carolwkc** [comment]
> > hi @dcs3spp, there is a typo in the content file only but it would be great to confirm with MDCB team.
> 
> @caroltyk for the MDCB environment variable typo fix in this PR, is it a typo in the source code also or just the docs?

@sredxny could you advice on this?

**Comment by letzya** [comment]
@buraksekili please check it with the squad. You probably need to update the source code, not the docs

**Review by sredxny — APPROVED** [review]
@buraksekili  thank you! ✅

**Comment by dcs3spp** [comment]
Thanks @sredxny did the source need updating too?

**Comment by dcs3spp** [comment]
@buraksekili The docs content in _/content/shared_ should be generated using [GitHub action](https://github.com/TykTechnologies/exp/actions/workflows/tyk-docs.yml) to synchronise between the source repository and docs. This includes config files generated from config.go files and OAS specs. There is an entry in the [docs contribution guide](https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/The+Docs+Bible+-+Docs+Contributors+Guide#PR-for-config-and-OAS-schema-updates).

For the MDCB config given in this PR it should read the docstring comments from this [config.go](https://github.com/TykTechnologies/tyk-sink/blob/de6f2418b2e263b02d5a53a935ae84ef6d0c40ca/config/config.go#L185) file and generate the markdown content with the corresponding environment variable generated. It will then raise a PR to store the generated Markdown in _/content/shared_ folder of docs repository for relevant target release.

@titpetric Had recently worked on updating the config generator used by the GHub action. If you inspect the files in the [PR](https://github.com/TykTechnologies/tyk-docs/pull/3956) that was generated then you should see that other config environment variables have similar updates.

@lghiur Can the [Tyk Docs Sync](https://github.com/TykTechnologies/exp/blob/main/.github/workflows/tyk-docs.yml) still be used or is it still in testing? If not safe yet then can we could merge this PR?

If it is ok to use, then @buraksekili If you could trigger 4 separate PRs using the [GitHub action](https://github.com/TykTechnologies/exp/actions/workflows/tyk-docs.yml) for MDCB with the following desintation branches:
 - release-5.2
 - release-5.1
 - release-5
 - master
 
 we can then import in the docs.
 
cc @letzya

**Comment by titpetric** [comment]
@dcs3spp not in testing, can continue to use it. Updates to the config info generator fix the dot issue in env variable names everywhere so this PR should not be needed

**Comment by dcs3spp** [comment]
> @dcs3spp not in testing, can continue to use it. Updates to the config info generator fix the dot issue in env variable names everywhere so this PR should not be needed

Thanks @titpetric @buraksekili I'll close the PR

**Pull request closed without merging**
