### PR TITLE
Moesif pump updates

### PR DESCRIPTION
**Pull request by matthewtanner91**

### CODE REVIEW

**Review by tbuchaillot — CHANGES_REQUESTED** [review]
Hi @matthewtanner91! Can you explain the changes of the config files for `.env` ones? I think if we want to include the env vars here, adding a "Setting X in your config file or Y env vars" should be better than just removing the config options from our docs.

**Comment by sedkis** [comment]
Updated the doc to include both JSON and ENV config methods :) @tbuchaillot  @matthewtanner91

**Review by tbuchaillot — APPROVED** [review]

**Review by marksou — APPROVED** [review]

**Pull request merged**
