### PR TITLE
Update redis-cluster.md

### PR DESCRIPTION
**Pull request by rewsmith**
As per [TT-6867](https://tyktech.atlassian.net/browse/TT-6867), provide more details on how to configure Redis Sentinel in Tyk, for example, indicating that multiple addresses are usually required, similar to Redis Cluster.

### CODE REVIEW

**Review by marksou — APPROVED** [review]

**Comment by rewsmith** [comment]
@marksou Just one comment on the latest changes from me.  On the Redis Cluster page, change `Our Gateway, Dashboard and Pump all support integration with both Redis Cluster` to `Our Gateway, Dashboard and Pump all support integration with Redis Cluster`

**Pull request merged**
