### PR TITLE
documented env vars of mdcb

### PR DESCRIPTION
**Pull request by sredxny**
Documented env vars of MDCB. Also moved the configs options to its own page like the other tyk components does.

### CODE REVIEW

**Comment by sredxny** [comment]
@buger  I merged https://github.com/TykTechnologies/tyk-sink/pull/167 which basically defines each of the configs options available in tyk-sink, however in this PR I do not see a job `config-gen` executed, am I missing something?

**Comment by sredxny** [comment]
Captura de Pantalla 2021-10-15 a la(s) 12 26 31 p  m
The doc now are generated from code....attached screenshot as proof that the text is loaded correctly

**Review by marksou — APPROVED** [review]
👍

**Review by tbuchaillot — APPROVED** [review]
It looks amazing 🚀

**Comment by sredxny** [comment]
@marksou hi, is safe to merge this?

**Comment by marksou** [comment]
@sredxny merging now!

**Pull request merged**
