### PR TITLE
CConvert article to gateway sharding

### PR DESCRIPTION
**Pull request by sedkis**
The multi-cloud section is no longer relevant.  I switched the narrative slightly so that this article now introduces the concept of Gateway sharding.

### CODE REVIEW

**Review by marksou — APPROVED** [review]
👍

**Comment by sedkis** [comment]
go ahead please and merge @marksou

**Comment by marksou** [comment]
@sedkis does this need to go in release-3.1 and release-3-lts as well as 3.2?

**Comment by sedkis** [comment]
Yes it does, but I'll defer to you for whether or not that's worth the effort

**Pull request merged**
