### PR TITLE
[TT-9022] Cache improvements

### PR DESCRIPTION
**Pull request by andyo-tyk**
## Related Issue (if applicable)
TT-9022

## Description
Restructured caching page into a section with multiple sub-pages

Note: one screenshot to be added

## Motivation and Context
Improves legibility of the documentation

### CODE REVIEW

**Comment by andyo-tyk** [comment]
Not sure how it got included in the commit, but tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md should not be there!

**Comment by dcs3spp** [comment]
@andyo-tyk Is this for Tyk release 5.1?

**Review by dcs3spp — COMMENTED** [review]
Hi @andy when I try to build the fork repository locally there are some references not found

References
- basic-config-and-security/reduce-latency/caching/global-cache
- basic-config-and-security/reduce-latency/caching/advanced-cache

In the markdown file basic-config-and-security/reduce-latency/caching.md these references are at lines 27 and 28.

**Comment by andyo-tyk** [comment]
Closing as one file incorrectly included. New PR raised.

**Pull request closed without merging**
