### PR TITLE
[DX-751]Every indexable page under /docs/ should have an absolute canonical URL

### PR DESCRIPTION
**Pull request by yurisasuke**
[Jira Ticket](https://tyktech.atlassian.net/browse/DX-751)
[
Preview Link](https://deploy-preview-3397--tyk-docs.netlify.app/docs/nightly)

## ScreenShot
Screenshot 2023-10-18 at 14 35 03

### CODE REVIEW

**Comment by letzya** [comment]
@Keithwachira how can we test it to see if it works?

**Comment by yurisasuke** [comment]
> @Keithwachira how can we test it to see if it works?

@letzya I have added a screenshot to show the result.

**Review by letzya — APPROVED** [review]

**Comment by letzya** [comment]
sorry, I meant to ask - how do we know it will solve our problem, but this question is not part of the pr...

**Pull request merged**
