### PR TITLE
[TD-484] Remove token from MDCB installation

### PR DESCRIPTION
**Pull request by alephnull**
These were the only places I found referencing the tokens.

### CODE REVIEW

**Review by marksou — APPROVED** [review]

**Review by craigtyk — APPROVED** [review]

**Comment by alephnull** [comment]
Needs to be merged to all versions.

**Comment by ermirizio** [comment]
@alephnull I have sugested some changes, since now the open packagecloud repo is **tyk-mdcb-stable** instead of **tyk-mdcb** . However there's no packages available in that packagecloud repo, and it has been never populated. Would you like me to do such thing? like donwloading all packages from the tyk-mdcb and uploading them to the tyk-mdcb-stable?

**Comment by alephnull** [comment]
> @alephnull I have sugested some changes, since now the open packagecloud repo is **tyk-mdcb-stable** instead of **tyk-mdcb** . However there's no packages available in that packagecloud repo, and it has been never populated. Would you like me to do such thing? like donwloading all packages from the tyk-mdcb and uploading them to the tyk-mdcb-stable?

Yes, Artem suggested copying over the packages for the last 18 months.

**Review by buger — APPROVED** [review]

**Pull request merged**
