### PR TITLE
Update version-5.0.md

### PR DESCRIPTION
**Pull request by carolwkc**
## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

### CODE REVIEW

**Comment by letzya** [comment]
@caroltyk labels please :)

**Comment by letzya** [comment]
@dcs3spp I made changes and @caroltyk needs to approve before we can merge :)

**Comment by carolwkc** [comment]
I can't approve my PR. But I've reviewed the change and it's good to go. Thanks @letzya @dcs3spp .

**Review by letzya — APPROVED** [review]

**Pull request merged**
