### PR TITLE
[DX-1592] Simplify FIPS page

### PR DESCRIPTION
**Pull request by andyo-tyk**
### Preview Link
https://deploy-preview-5177--tyk-docs.netlify.app/docs/nightly/developer-support/special-releases-and-features/fips-release/#fips-compliant-cryptographic-operations

### Description
Reduced duplication, corrected some typos, slight restructure to improve flow through the page.

___

### **PR Type**
Documentation

___

### **Description**
- Reduced duplication and corrected typos in the FIPS release documentation.
- Added detailed sections on the importance of FIPS compliance in API management.
- Clarified configuration steps and compliance details for Tyk's FIPS-compliant products.
- Improved overall readability and structure of the document.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>fips-release.md</strong><dd><code>Simplified and enhanced FIPS release documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/developer-support/special-releases-and-features/fips-release.md

<li>Reduced duplication of content.<br> <li> Corrected typos and improved readability.<br> <li> Added detailed sections on the importance of FIPS compliance in API <br>management.<br> <li> Clarified configuration steps and compliance details.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5177/files#diff-b44c128229d177eab79e9acd572d10e7d982dc4bb8281d1297a6eae70dc514a0">+48/-71</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
PR LGTM, @buger would you be able to peer review and if ok approve?

**Review by buger — APPROVED** [review]

**Comment by buger** [comment]
All good

**Pull request merged**
