### PR TITLE
[DX-967] Update setup-multiple-gateways.md

### PR DESCRIPTION
**Pull request by SonjaChevre**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link
https://deploy-preview-3912--tyk-docs.netlify.app/docs/nightly/deployment-and-operations/tyk-open-source-api-gateway/setup-multiple-gateways/
<br>

### Description
Improved description at the top, to make it clearer that this is a scenario for OSS and not commercial users. 
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

### CODE REVIEW

**Review by carolwkc — APPROVED** [review]
LGTM

**Comment by SonjaChevre** [comment]
hi @letzya @dcs3spp - would it be possible to move this page to the Deployment and Operations section for Tyk OSS (https://tyk.io/docs/apim/open-source/)? 

That's not a Tyk GW setting per se, but a deployment pattern that is only relevant when using OSS.

**Review by dcs3spp — APPROVED** [review]
@SonjaChevre PR LGTM. Will check with Rich re moving the content as suggested. Thanks for the peer review @caroltyk 

In the meantime @SonjaChevre can the changes that I have approved be merged and released. Then we can raise separate ticket to discuss the suggested location?

**Pull request merged**
