### PR TITLE
hide getting started for tyk cloud

### PR DESCRIPTION
**Pull request by dcs3spp**
hide getting started for tyk cloud - based on this pr https://github.com/TykTechnologies/tyk-docs/pull/2963

The page to remove - https://deploy-preview-3218--tyk-docs.netlify.app/docs/nightly/tyk-cloud/getting-started/

### CODE REVIEW

**Comment by letzya** [comment]
@SonjaChevre you asked to hide this page (in #2963). Are you sure about that? 
1. We don't have anywhere else link to the glossary
2. We don't have this diagram anywhere else

**Comment by SonjaChevre** [comment]
Sorry for the misunderstanding! Before hiding it, I want to first improve the current content, to make sure everything on these pages are already covered in the content.

But the goal should be to have only 1 tutorial for Cloud - the quick one.

**Comment by dcs3spp** [comment]
@SonjaChevre Shall I keep this PR open as a draft PR for the time being? Then when the content has been changed we can open the PR again?

**Comment by SonjaChevre** [comment]
yes, good idea, thanks!

**Comment by letzya** [comment]
@dcs3spp @SonjaChevre We actually have plans to not keep parked PRs as drafts for a very long time as it counted towards our open PRs in the queue. Can we please close it? Informations stays and if you have a Jira ticket for it or if you remember it then it doesn't really matter if it's closed or draft

**Comment by letzya** [comment]
closing per my message above @SonjaChevre. Let me know if not clear, it's a reversible action anyway :)

**Pull request closed without merging**
