### PR TITLE
[TT-8959/TT-9613] Add endpoint level cache timeout doc

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR adds documentation for the endpoint level cache timeout value.

### CODE REVIEW

**Comment by dcs3spp** [comment]
@furkansenharputlu PR looks good to me. Please label with targeted release.

**Review by jeffy-mathew — APPROVED** [review]

**Comment by andyo-tyk** [comment]
I think this has been added to the wrong place in the page - it's been added to "Selective caching by body value", it should be in "Selective caching by endpoint" as that is the use case where a user might be particularly interested in setting different timeouts for different endpoints.

**Comment by dcs3spp** [comment]
@furkansenharputlu per comment made by @andyo-tyk should the timeout field moved into the cache by endpoint section?

**Review by dcs3spp — CHANGES_REQUESTED** [review]
@furkansenharputlu per comment made by @andyo-tyk should the timeout field moved into the cache by endpoint section?

**Comment by furkansenharputlu** [comment]
Imho, I think `timeout` belongs to the correct place. Things should move as a block, the `timeout` is the inner piece and it belongs to the correct configuration example.

**Comment by andyo-tyk** [comment]
I will create a new Jira ticket for a restructuring of this page - in fact there should be a page dedicated to per-endpoint caching so will probably move all of that to a new page.

Please feel free to approve this PR, @dcs3spp

**Review by dcs3spp — APPROVED** [review]

**Pull request merged**
