### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by marksou**
Add versioning via Dashboard section

### CODE REVIEW

**Comment by letzya** [comment]
@lghiur please review if you want to merge this PR

**Review by lghiur — APPROVED** [review]

**Comment by buger** [comment]
@lghiur all green ^

**Comment by lghiur** [comment]
@letzya this can be merged

**Comment by letzya** [comment]
@lghiur to 4.3 right?

**Comment by lghiur** [comment]
@letzya yes, this is needed for 4.3

**Pull request merged**
