### PR TITLE
Update reference to commit hash

### PR DESCRIPTION
**Pull request by munkiat**
Fixed a typo pointing to wrong version hash (5.1.2) should be (5.2.1)

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

### CODE REVIEW

**Review by sharadregoti — APPROVED** [review]

**Comment by letzya** [comment]
@sharadregoti I was looking for a proof that it's 5.2.1 ;) and here it is https://github.com/TykTechnologies/tyk/commit/ffa83a27d3bf793aa27e5f6e4c7106106286699d

**Pull request merged**
