### PR TITLE
[DX-603] add deprecated notes for old helm chart page

### PR DESCRIPTION
**Pull request by carolwkc**
[Preview hybrid gateways](https://deploy-preview-3072--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways)
[Preview ce-helm charts](https://deploy-preview-3072--tyk-docs.netlify.app/docs/nightly/tyk-oss/ce-helm-chart/)
[Preview ce-kubernetes](https://deploy-preview-3072--tyk-docs.netlify.app/docs/nightly/tyk-oss/ce-kubernetes)

### CODE REVIEW

**Comment by dcs3spp** [comment]
@caroltyk I have added preview links to the PR. If can get a peer review done then I think we can merge and release

**Review by dcs3spp — APPROVED** [review]
@caroltyk I have added preview links to the PR. Pr looks good to me. If can get a peer review done then I think we can merge and release

**Review by andrei-tyk — APPROVED** [review]

**Review by buraksekili — APPROVED** [review]

**Comment by carolwkc** [comment]
@dcs3spp thanks for assisting. Peer review done

**Pull request merged**
