### PR TITLE
update mdcb caching doc

### PR DESCRIPTION
**Pull request by gregdelhon**

### CODE REVIEW

**Comment by gregdelhon** [comment]
@marksou tiny one - can be merged now.

**Comment by marksou** [comment]
Hi @gregdelhon shouldn't we just say from version 3.09, or am I missing something?

**Comment by gregdelhon** [comment]
@marksou it's an odd one. 3.0.9 will come after 4.0. So technically it's important to mention both for the time being.

**Comment by marksou** [comment]
@gregdelhon As 4.0 hasn't officially been released, I'm assuming it's safe to leave merging this until the 4.0 release branch is live?

**Comment by gregdelhon** [comment]
Yep that's fine. @marksou

**Review by marksou — APPROVED** [review]

**Pull request merged**
