### PR TITLE
[DX-111] New look&feel - Color changes

### PR DESCRIPTION
**Pull request by marksou**
First go at changes to the docs pages suggested by Jen

### CODE REVIEW

**Comment by letzya** [comment]
The wave is located in a different place than in the current master and crosses the text 
https://tyk.io/docs//tyk-on-premises/
https://deploy-preview-2076--tyk-docs.netlify.app/docs/nightly/tyk-on-premises/

image

**Review by letzya — CHANGES_REQUESTED** [review]
https://github.com/TykTechnologies/tyk-docs/pull/2076#issuecomment-1326597927

**Comment by marksou** [comment]
> [#2076 (comment)](https://github.com/TykTechnologies/tyk-docs/pull/2076#issuecomment-1326597927)

You are comparing the desktop (left) with the mobile version (right). I haven't done anything to the shape of the wave as part of this PR.

**Review by letzya — CHANGES_REQUESTED** [review]
1. white on grey background for the code snippets
image
2. Tiles' colour needs update
3. We need to remove the waves and keep the top only
image

**Comment by letzya** [comment]
> https://github.com/TykTechnologies/tyk-docs/pull/2076#issuecomment-1326597927

>You are comparing the desktop (left) with the mobile version (right). I haven't done anything to the shape of the wave as part of this PR.

No, I'm not, it was full screen, just made the two fit the screen for the screenshot. Is it ok on your end? I was wondering why it's happening

**Review by letzya — CHANGES_REQUESTED** [review]
From Guillermo: 
it would be maybe useful on the front-end to add a "dark" class to the body and do modifications for the colours if that class is active. So it would be easier to change it later on to implement the light mode.

**Comment by letzya** [comment]
We'll do a new one

**Pull request closed without merging**
