### PR TITLE
[DX-1112] Add further details on keycloak client scopes for DCR

### PR DESCRIPTION
**Pull request by rewsmith**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link
[](https://deploy-preview-4163--tyk-docs.netlify.app/docs/nightly/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration/)
<br>

### Description
To avoid issues with Keycloak DCR it should be made clear that Client scopes are created with type `Optional`, and that in older versions of keycloak the method by which type is set differs.  @slega 
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

___

## **Type**
documentation

___

## **Description**
- Added a note clarifying that initial access tokens for Dynamic Client Registration (DCR) are optional, depending on the provider.
- Highlighted the necessity of setting Keycloak client scopes to `Optional` to ensure correct operation.
- Provided instructions for configuring client scopes in older versions of Keycloak, including a screenshot for clarity.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>dynamic-client-registration.md</strong><dd><code>Enhanced Keycloak DCR Documentation with Client Scope Details</code></dd></summary>
<hr>

tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
<li>Added a note on the optionality of initial access tokens for DCR with <br>various providers.<br> <li> Emphasized the importance of setting Keycloak client scopes to <br><code>Optional</code> for proper functionality.<br> <li> Included guidance for configuring client scopes in older versions of <br>Keycloak.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4163/files#diff-dae8afc86acebb3da945f81b1896a65e103528c1bdf359cc04cf654eea38ab4c">+13/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by slega — APPROVED** [review]

**Comment by slega** [comment]
LGTM!

**Review by dcs3spp — APPROVED** [review]
Thanks Andy, PR LGTM

**Pull request merged**
