### PR TITLE
[DX-1275] Update linkages to Azure Cosmos DB for MongoDB

### PR DESCRIPTION
**Pull request by wmwxwa**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

### CODE REVIEW

**Review by letzya — APPROVED** [review]

**Comment by wmwxwa** [comment]
#sign-off

**Comment by letzya** [comment]
@wmwxwa since you are in tyk org could you please open prs as branches and not forks. If you don't then the last 2 CI jobs will not run automatically for you.

**Comment by wmwxwa** [comment]
> @wmwxwa since you are in tyk org could you please open prs as branches and not forks. If you don't then the last 2 CI jobs will not run automatically for you.

I'm actually not in tyk org :-)

**Comment by dcs3spp** [comment]
Thanks for contributing to Tyk docs @wmwxwa

**Pull request merged**
