### PR TITLE
[TT-5912] tyk-sync version command

### PR DESCRIPTION
**Pull request by tbuchaillot**
Adding docs and an example for  Tyk-Sync version command added in tyk-syn 1.2.2.

### CODE REVIEW

**Review by marksou — APPROVED** [review]
I committed a couple of minor edits.

**Review by andyo-tyk — APPROVED** [review]
Matches the wording approved for the readme, so I'm happy with this. Thanks.

**Comment by tbuchaillot** [comment]
@marksou can we merge?

**Pull request merged**
