### PR TITLE
change from old field name aggregates_ignore_tags  to the new field n…

### PR DESCRIPTION
**Pull request by letzya**
…ame ignore_tag_prefix_list

### CODE REVIEW

**Review by komalsukhani — APPROVED** [review]

**Comment by letzya** [comment]
@marksou was approved, ready for merge.

**Review by marksou — APPROVED** [review]

**Comment by letzya** [comment]
@marksou please check again, there was an error in my pr

**Review by marksou — APPROVED** [review]

**Review by sredxny — APPROVED** [review]

**Comment by letzya** [comment]
@marksou

**Comment by letzya** [comment]
@marksou can you please merge?

**Review by komalsukhani — APPROVED** [review]

**Pull request merged**
