### PR TITLE
Update the private key definition in certs

### PR DESCRIPTION
**Pull request by marksou**

### CODE REVIEW

**Comment by letzya** [comment]
@marksou not sure I understand the pr.

**Comment by letzya** [comment]
@marksou ?

**Comment by marksou** [comment]
If I remember, @buger asked me to look at the wording. which I did.

**Review by letzya — APPROVED** [review]
Seems very similar. Hope I didn't miss anything

**Review by letzya — CHANGES_REQUESTED** [review]
@marksou on 2nd thought - can you please explain me the actual difference? I don't understand it. thanks

**Comment by buger** [comment]
The change here still make sense from grammar point of view, but it is not correct in a sentence about fallback. Using "private key" is not correct, is should say that it just falls back to `secret` field.

**Pull request merged**
