### PR TITLE
[DX-1407] Tyk Streams Workflow Processor

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1407](https://tyktech.atlassian.net/browse/DX-1407)

---

### Preview Link

- [processing pipelines](https://deploy-preview-5052--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines)
- [resources](https://deploy-preview-5052--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/common-configuration/resources)
- [workflow processor](https://deploy-preview-5052--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/processors/workflow)

### Description

Adds Tyk Streams workflow processor and adds resources guide with comments added for review.
Also adds process pipelines section for review.

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

[DX-1407]: https://tyktech.atlassian.net/browse/DX-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Added new documentation for processing pipelines in Tyk Streams, explaining their configuration and benefits.
- Introduced a section on resources, detailing their reusability and advantages in Tyk Streams configurations.
- Provided a comprehensive guide on the workflow processor, including configuration, examples, and error handling.
- Updated the menu configuration to include links to the new documentation sections.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>processing-pipelines.md</strong><dd><code>Add documentation for processing pipelines in Tyk Streams</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md

<li>Introduced a new section on processing pipelines.<br> <li> Explained the use of the <code>pipeline</code> section in Tyk Streams <br>configuration.<br> <li> Provided a YAML example for configuring processing pipelines.<br> <li> Described the use of <code>threads</code> for parallel execution.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5052/files#diff-23d021e24523f3121d716435546ded4aea34c918c0f57c4909bf34a1b1952331">+29/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>resources.md</strong><dd><code>Introduce resources documentation for Tyk Streams</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/resources.md

<li>Added a new section on resources in Tyk Streams.<br> <li> Explained the concept of resources and their reusability.<br> <li> Provided YAML examples for defining and using resources.<br> <li> Discussed the advantages of using resources.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5052/files#diff-adbf3279fe952a5e62f463eb0410e25b292c72620a7567a0f5fb0c7fa756c98f">+71/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>workflow.md</strong><dd><code>Comprehensive guide for workflow processor in Tyk Streams</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/processors/workflow.md

<li>Added comprehensive documentation for the workflow processor.<br> <li> Explained common and advanced configuration fields.<br> <li> Provided examples of automatic ordering and conditional branches.<br> <li> Discussed error handling and structured metadata.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5052/files#diff-6fcc0bbc53a75f2c7d09ed4994c3888b86fa4ad52657dac392c30f761ff3345f">+341/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Update menu to include new Tyk Streams documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml

<li>Added new menu entries for Workflow, Processing Pipelines, and <br>Resources.<br> <li> Updated the menu structure to include new documentation sections.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5052/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+12/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by dcs3spp** [comment]
Closing until ready for review

**Review by letzya — APPROVED** [review]

**Comment by dcs3spp** [comment]
Closing depends on switch processor in unreleased PR #5017 need to add link to switch processor. Will reopen and release once #5017 has been released. Also contains input and output to file in an example which needs replacing due to security issues

**Comment by dcs3spp** [comment]
Switch processor link, closing until input / output file example replaced in resources content

**Comment by dcs3spp** [comment]
closing PR until investigated conflicts in menu.yaml

**Pull request merged**
