### PR TITLE
[DX-1422] add cert manager prereq

### PR DESCRIPTION
**Pull request by zalbiraw**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1422](https://tyktech.atlassian.net/browse/DX-1422)

---

### Preview Link

<br>
https://deploy-preview-4812--tyk-docs.netlify.app/docs/nightly/tyk-stack/tyk-operator/installing-tyk-operator/#prerequisites

### Description

<br>
Add cert manager as a pre req to operator install page
#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

___

### **PR Type**
documentation

___

### **Description**
- Added `cert-manager v1.8+` as a prerequisite for installing Tyk Operator.
- Updated documentation to reflect the new requirement.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>installing-tyk-operator.md</strong><dd><code>Add cert-manager to Tyk Operator prerequisites</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
- Added `cert-manager v1.8+` to the prerequisites section.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4812/files#diff-0b4360968306ecca2c98ec75cb33de17643269cf4ce999c6fd93b789df611d3a">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

[DX-1422]: https://tyktech.atlassian.net/browse/DX-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by carolwkc — APPROVED** [review]
Thanks

**Comment by dcs3spp** [comment]
@zalbiraw @caroltyk should this be released to current release 5.3 only?

**Review by dcs3spp — APPROVED** [review]
PR LGTM

**Pull request merged**
