### PR TITLE
Added additional details on the health-check endpoint

### PR DESCRIPTION
**Pull request by LLe27**
We had a support ticket that a client upgraded to v3.0.9 and was having issues on the health-check API endpoint. I added important details on the use of that endpoint. Thanks to @OldStubbsy for providing that guidance! This documentation will provide guidance for users configuring the `control_api_port` and are receiving `404 page not found error`.

### CODE REVIEW

**Review by marksou — COMMENTED** [review]
Hi @LLe27 the changes to the gateway-config and gateway-swagger need to be made in the Tyk repository, not the docs as these get automatically pulled into the docs from that repo. Contact me on Slack if you want to discuss.

**Comment by letzya** [comment]
Hi, 2 of these files are auto gen so they need to be updated in the source repo, tyk repo.

**Review by letzya — CHANGES_REQUESTED** [review]
pr my comment

**Comment by letzya** [comment]
@andyo-tyk this pr updates auto-gen docs so needs to be closed but we need to create jira tickets for it. Could you please review the changes and add the tickets if needed?

**Comment by dcs3spp** [comment]
Raised tickets with Tyk Gateway to update config and swagger for helath check endpoints
- [https://tyktech.atlassian.net/browse/TT-9491](https://tyktech.atlassian.net/browse/TT-949)
- [https://tyktech.atlassian.net/browse/TT-9489](https://tyktech.atlassian.net/browse/TT-9489)

**Pull request closed without merging**
