### PR TITLE
[DX-975]Update data-graphs-api.md

### PR DESCRIPTION
**Pull request by letzya**
Improve formatting
Fixed error in format (currently the values of the JSON the table look empty)
Added description
Added official links

[preview](https://deploy-preview-3941--tyk-docs.netlify.app/docs/nightly/tyk-apis/tyk-dashboard-api/data-graphs-api)

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by buraksezer — APPROVED** [review]

**Review by dcs3spp — APPROVED** [review]
@letzya PR LGTM.

I like the external links added, scripts and the new copy icon feature

**Pull request merged**
