### PR TITLE
[DX-1407] Tyk Streams: Sync response

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1407](https://tyktech.atlassian.net/browse/DX-1407)

---

### Preview Link

- [preview - http_client input](https://deploy-preview-5047--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/inputs/http-client)
- [preview - http_client output](https://deploy-preview-5047--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/outputs/http-client)
- [preview - http processor](https://deploy-preview-5047--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/processors/http)

### Description

Adds Sync Response and dependencies

Note: PR has link errors since depends on [batch and dependencies PR](https://github.com/TykTechnologies/tyk-docs/pull/5017)

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

[DX-1407]: https://tyktech.atlassian.net/browse/DX-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Added comprehensive documentation for various Tyk Streams configurations including inputs, outputs, processors, and scanners.
- Introduced new guides and examples for configuring and using Tyk Streams features like synchronous responses and HTTP clients.
- Updated the menu structure to incorporate new documentation pages and ensure easy navigation.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>13 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>generate.md</strong><dd><code>Add documentation for Generate Input configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/generate.md

<li>Added documentation for the <code>Generate Input</code> configuration.<br> <li> Included examples for cron scheduled processing and generating test <br>data.<br> <li> Detailed configuration fields like <code>mapping</code>, <code>interval</code>, <code>count</code>, etc.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-2794a3d5a96386a0d021c2d3aee86fcb640b1a85c559caa00d1cdb9bce18bcbe">+126/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>http-client.md</strong><dd><code>Document Http Client input configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md

<li>Added documentation for configuring <code>Http Client</code> input.<br> <li> Explained common and advanced configuration fields.<br> <li> Provided examples for basic pagination.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-b11b4a6e8a4dd21b0a313a6a0f8ab8c5a857428eae5e2977199300651ab0f349">+745/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>http-client.md</strong><dd><code>Document Http Client output configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md

<li>Added documentation for configuring <code>Http Client</code> output.<br> <li> Explained fields like <code>url</code>, <code>verb</code>, <code>headers</code>, and batching options.<br> <li> Discussed performance benefits and response propagation.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-c419ced5b9375f06cf7260b38a7724e676a24a3913c15049006b314d91fb833c">+822/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>stdout.md</strong><dd><code>Update stdout output configuration tags</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md

- Added `stdout` tag to the existing configuration documentation.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-29b6efd59255fdd811cb937fe1002cef68100d27dbcfa44f0b663a534d82d2d4">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sync-response.md</strong><dd><code>Document Sync Response output configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/sync-response.md

<li>Added documentation for <code>Sync Response</code> output configuration.<br> <li> Explained how it returns message payloads to input origins.<br> <li> Provided example usage with <code>http_server</code> input.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-a2bfb787a8d0d9c2a71565a27d7010d792a6895f4d1db48fc05094c9e93f57a6">+38/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>http.md</strong><dd><code>Document Http processor configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/processors/http.md

<li>Added documentation for configuring <code>Http</code> processor.<br> <li> Detailed fields like <code>url</code>, <code>verb</code>, <code>headers</code>, and error handling.<br> <li> Included example for branched request processing.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-c0d7e04bdd7e7171ec2ead3d7a7ba625f2bf68b0aae16dc05c845623d04d92a7">+679/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sync-response.md</strong><dd><code>Document Sync Response processor configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sync-response.md

<li>Added documentation for <code>Sync Response</code> processor.<br> <li> Explained how it adds payloads as synchronous responses.<br> <li> Mentioned compatibility with <code>http_server</code> input.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-d73d15030164c979259db34662750a14e2d8ee152c7a3a7f67097fcd2c8a0f62">+17/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>csv.md</strong><dd><code>Document CSV scanner configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/csv.md

<li>Added documentation for <code>CSV</code> scanner configuration.<br> <li> Explained fields like <code>custom_delimiter</code> and <code>parse_header_row</code>.<br> <li> Described metadata added by the scanner.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-56f0c3e11d2abeec6a8f57d9adf3211325338b8f900dae3da47776a0dcc8f9cc">+57/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>lines.md</strong><dd><code>Document Lines scanner configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/lines.md

<li>Added documentation for <code>Lines</code> scanner configuration.<br> <li> Explained fields like <code>custom_delimiter</code> and <code>max_buffer_size</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-19399b6622fc396ef3d43c7fce96188bee7a28fe3efbfb85c89b2f3424fb80ac">+32/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>overview.md</strong><dd><code>Add overview of scanners in Tyk Streams</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/overview.md

<li>Added an overview of scanners in Tyk Streams.<br> <li> Explained the purpose and configuration of scanners.<br> <li> Provided examples for using scanners with file inputs.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-51c78acc8cecec0701591c161da9cd3d250cfe5285449e05f166f529e287373b">+36/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>re-match.md</strong><dd><code>Document Regular Expression Match scanner</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/re-match.md

<li>Added documentation for <code>Regular Expression Match</code> scanner.<br> <li> Explained fields like <code>pattern</code> and <code>max_buffer_size</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-a2b093a1fc1f890055f59ed08dece55401287209b80cac655bb09bc28958acf4">+37/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>switch.md</strong><dd><code>Document Switch scanner configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/switch.md

<li>Added documentation for <code>Switch</code> scanner configuration.<br> <li> Explained how to dynamically select child scanners.<br> <li> Provided example for switching based on file name.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-59f93bf595ce3b0be5a0d3081949096d332602331bd5abb969dc5e3836d13151">+68/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sync-responses.md</strong><dd><code>Add guide on Synchronous Responses in Tyk Streams</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/guides/sync-responses.md

<li>Added guide on Synchronous Responses in Tyk Streams.<br> <li> Explained routing processed messages back to inputs.<br> <li> Included examples for using sync responses with HTTP server.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-e63c62d4e738ca4a44d405422fbf16b3f4223982ec82964246f1a228b57842cf">+133/-0</a>&nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Update menu structure for new documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml

<li>Updated menu structure to include new documentation pages.<br> <li> Added entries for new configurations and guides.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5047/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+52/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by dcs3spp** [comment]
Closing PR in draft status and requires scanner component, http processor and generate input

**Comment by dcs3spp** [comment]
Generated previews for review and closing PR, until determine requirements of org regarding TLS certificates from secrets environment variables and files.

**Review by letzya — APPROVED** [review]

**Comment by dcs3spp** [comment]
Closing until discussed TLS, Authentication, rate limit and input files issues

**Comment by dcs3spp** [comment]
Closing until resolve build errors

**Pull request merged**
