### PR TITLE
Add gRPC proxy info.

### PR DESCRIPTION
**Pull request by marksou**

### CODE REVIEW

**Review by davegarvey — COMMENTED** [review]
I think that the topic of gRPC proxying should be separate from gRPC as a middleware. It doesn't feel right from an information architecture perspective.

We have a page for TCP proxy, so gRPC should be handled in the same way.

**Comment by buger** [comment]
It is right. gRPC proxying should be separate section.

**Comment by marksou** [comment]
@davegarvey  I've now created a new page.

**Comment by marksou** [comment]
Given that this is caught up with the restructure, I'll add the new file into the new structure and merge, taking note of the other amended files

**Pull request merged**
