### PR TITLE
[DX-1407] Tyk Streams: Try Processor

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1407](https://tyktech.atlassian.net/browse/DX-1407)

---

### Preview Link

[preview](https://deploy-preview-5010--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-streaming/configuration/processors/try)

### Description

Add Tyk Streams Try Processor

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

[DX-1407]: https://tyktech.atlassian.net/browse/DX-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Added a new document explaining the Try processor, including configuration examples and usage scenarios.
- Provided information on nesting the Try processor within a catch block.
- Updated the Catch processor documentation to include a link to the error handling documentation.
- Updated the menu configuration to include the Try processor.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>catch.md</strong><dd><code>Add link to error handling documentation in Catch processor</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/processors/catch.md

- Added a link to the error handling documentation.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5010/files#diff-4174aa9eb5bce0803a14c1213401c7d475f12f57ea4ea3834c8d062c2b87188a">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>try.md</strong><dd><code>Add documentation for Try processor with examples</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-streaming/configuration/processors/try.md

<li>Added a new document explaining the Try processor.<br> <li> Included configuration examples and usage scenarios.<br> <li> Provided information on nesting within a catch block.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5010/files#diff-a2e3436dbbe32433b1feaa743cc4c24cc6af55a8885294ce56e90fe79dc1f111">+53/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Update menu configuration to include Try processor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml

- Added Try processor to the menu configuration.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5010/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by dcs3spp** [comment]
Closing PR until ready for review

**Review by buger — APPROVED** [review]

**Comment by dcs3spp** [comment]
Many thanks @buger

**Pull request merged**
