### PR TITLE
[DX-1231] Update upgrading-tyk.md

### PR DESCRIPTION
**Pull request by letzya**
## **User description**
https://deploy-preview-4338--tyk-docs.netlify.app/docs/nightly/upgrading-tyk/#upgrade-tyk-components-in-tyk-cloud

### For internal users - Please add a Jira DX PR ticket to the subject!
<be>

The anchor should be upgrade CP not edit CP
---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

## **Type**
documentation

___

## **Description**
- Corrected the hyperlink in the Tyk Cloud section of the upgrading guide to point to the "upgrade control planes" section instead of "edit control planes".

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>upgrading-tyk.md</strong><dd><code>Update Upgrade Guide Link in Tyk Cloud Section</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/upgrading-tyk.md
<li>Updated the link to guide users on upgrading Tyk components in Tyk <br>Cloud, specifically changing the anchor from "edit control planes" to <br>"upgrade control planes".<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4338/files#diff-221a7f51df6259b8406c9f416126d25f2fb55b17cac68b4227a85efc90ae751b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by nerdydread — APPROVED** [review]
This change looks good to me.  I viewed the updated page and clicked through the link to make sure it resolved properly.

**Review by dcs3spp — APPROVED** [review]
PR LGTM, @Fadzli-fast @mitjaziv would you be able to peer review for merge and release

**Pull request merged**
