### PR TITLE
[TT-13125] Update documentation for 5.0 LTS

### PR DESCRIPTION
**Pull request by buger**
Triggered by: titpetric

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: 5.0 LTS
Changes sourced from: release-5-lts
Config info generator branch: main

Note: Retrigger after config generator update (branch suffix: release)

JIRA: https://tyktech.atlassian.net/browse/TT-13125

### CODE REVIEW

**Review by lghiur — APPROVED** [review]

**Review by lghiur — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Review by andyo-tyk — APPROVED** [review]

**Review by sharadregoti — APPROVED** [review]

**Comment by sharadregoti** [comment]
release to release-5.5

**Pull request merged**
