### PR TITLE
Fix sundry docs

### PR DESCRIPTION
**Pull request by alephnull**
- goplugin instructions
- AWS instructions for Standalone

### CODE REVIEW

**Review by marksou — APPROVED** [review]

**Comment by marksou** [comment]
@alephnull Hi Alok, note that this page has moved within the menu structure. Sorry!

**Comment by alephnull** [comment]
@marksou Sorry, could you tell me what I've done wrong?

**Comment by marksou** [comment]
Hi @alephnull it's just that tyk-docs/content/customise-tyk/plugins/golang-plugins/golang-plugins.md

Is now tyk-docs/content/plugins/golang-plugins/golang-plugins/

Hence the merge conflict

**Comment by alephnull** [comment]
@marksou Is this better? I can see my changes in tyk-docs/content/plugins/golang-plugins/golang-plugins/golang-plugins.md

**Comment by marksou** [comment]
@alephnull Yes, do you want me to merge now?

**Comment by alephnull** [comment]
Please do merge this. But push to production only with the 2.9.3 release.

**Pull request merged**
