### PR TITLE
[DX-1435] Update stable branch updator for release 5.4.0

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1435](https://tyktech.atlassian.net/browse/DX-1435)

---

### Preview Link

N/A

### Description

Update stable branch updator to ref 5.4 branch ready for release

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

[DX-1435]: https://tyktech.atlassian.net/browse/DX-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
configuration changes

___

### **Description**
- Updated the stable branch updater workflow to reference the new `release-5.4` branch.
- Modified the workflow trigger condition to match the new branch.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>stable-updater.yaml</strong><dd><code>Update stable branch updater for release 5.4.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.github/workflows/stable-updater.yaml

<li>Updated branch reference from <code>release-5.3</code> to <code>release-5.4</code>.<br> <li> Modified the condition to trigger the workflow based on the new <br>branch.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4829/files#diff-f7fcfa8300d37bebb207c3b4355f4361cd5c0cbf353e5dff62a50777179ee38d">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by dcs3spp** [comment]
Closing in preparation of release 5.4.0

**Review by yurisasuke — APPROVED** [review]

**Pull request merged**
