### PR TITLE
Update 3rd-party-identity-providers.md

### PR DESCRIPTION
**Pull request by rewsmith**
Updated requirements and dependencies to mention TIB based SSO also available for Tyk Multi-Cloud

### CODE REVIEW

**Comment by marksou** [comment]
@rewsmith Do we need to mention how they get the feature enabled? Via account manager, etc? Have also formatted the note.

**Comment by rewsmith** [comment]
@marksou That's a good call.  I'll add some appropriate words.

**Comment by rewsmith** [comment]
@marksou Appropriate words now added

**Review by marksou — APPROVED** [review]
👍

**Pull request merged**
