### PR TITLE
[DX-622]Change link colors and lines

### PR DESCRIPTION
**Pull request by yurisasuke**
### For internal users - please add a Jira DX PR ticket to the subject!
DX-622
---
### Preview Link
https://deploy-preview-3097--tyk-docs.netlify.app/docs/nightly/getting-started/

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — COMMENTED** [review]
@keith Should the grey horizontal borders be light purple colour also, similar to the sidebar line?

**Comment by yurisasuke** [comment]
> @keith Should the grey horizontal borders be light purple colour also, similar to the sidebar line?

Yes I have not finished working on this Pr.Am trying to figure out where that  horizontal borders is(the css for it). Let me mark this as draft

**Review by dcs3spp — APPROVED** [review]
nice! lgtm

**Pull request merged**
