### PR TITLE
added video instructions on setting up tyk cloud account

### PR DESCRIPTION
**Pull request by LLe27**
There was a **"Watch our video on setting up your Tyk Cloud account."** section under the **"1. Task 1 - Create Your Account"** that did not have a video on setting up the cloud account. Instead I had to search YouTube for it. This provides ease of access to users.

### CODE REVIEW

**Comment by marksou** [comment]
Hi @LLe27 that video was done with an earlier release of Tyk Cloud. We should remove the text about the video until we've made an updated version.

**Comment by LLe27** [comment]
Hi @marksou. Thanks for clarification. I am not too sure about the product workflow so I want to do what is best for everyone. I can do a few things:
- [x] Remove the section including the text and video
- [ ] Add comments in the readme file for future references (not sure how future updates are tracked).

Let me know what works best for you. Thanks.

**Comment by marksou** [comment]
Hi @LLe27 I think removing the section would be best. We'll get an updated video created 😀

**Comment by LLe27** [comment]
@marksou - video section has been removed :). Let me know if there's anything else that is needed for this PR.

**Comment by marksou** [comment]
Thanks @LLe27 that's all for this one.

**Comment by LLe27** [comment]
Hey @marksou 

I just wanted to ask a quick question. I am still new at Tyk and not entirely sure about the process. In terms for merging the request, is it done by one of the engineers or would I request authorization etc.

Thanks,
L

**Comment by marksou** [comment]
Apologies @LLe27 I forgot to reply yesterday. Once an approval review has been submitted, myself or Leo can merge to master and then sort out the docs versions the change should be made to. I'll merge this one today.

**Review by marksou — APPROVED** [review]

**Comment by LLe27** [comment]
@marksou thanks for the clarification 👍

**Pull request merged**
