### PR TITLE
Right Sidebar active changes in js

### PR DESCRIPTION
**Pull request by Vish10Tyk**
Right Sidebar active changes in js

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description
Issue resolved for change in color in right side menu and sub menu, when directly open via URL.

To Test after taking merge request open the below URL and it should open Api-Documentation right side menu with change in color.
https://deploy-preview-4165--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-dashboard/release-notes/version-5.2/#api-documentation

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Comment by letzya** [comment]
@Vish10Tyk can you please add info in the description section on what is this PR about and how it was tested? Also, share links of specific pages to show/prove the improvement.

**Comment by letzya** [comment]
@Keithwachira this PR needs to be approved in Netlify

**Comment by yurisasuke** [comment]
> @Keithwachira this PR needs to be approved in Netlify

@letzya  I have approved it and added a preview url to the description

**Comment by letzya** [comment]
A few issues:
1.
image

2. 
image

3. I can't scroll up

**Comment by yurisasuke** [comment]
replaced by https://github.com/TykTechnologies/tyk-docs/pull/4233

**Pull request closed without merging**
