### PR TITLE
[TT-1574] Multiple analytics keys

### PR DESCRIPTION
**Pull request by tbuchaillot**
Adding docs for new config option `enable_multiple_analytics_keys`

### CODE REVIEW

**Review by matiasinsaurralde — APPROVED** [review]

**Review by sredxny — APPROVED** [review]
LGTM!

**Review by marksou — APPROVED** [review]
👍

**Comment by tbuchaillot** [comment]
Added config option for MDCB

**Review by marksou — APPROVED** [review]
👍

**Pull request merged**
