### PR TITLE
TT-2693 added example of grpc data streaming

### PR DESCRIPTION
**Pull request by sredxny**
added example for bidirectional data streaming in grpc, with service exposed in https but grpc server running in h2. This corresponds to the ticket https://tyktech.atlassian.net/browse/TT-2693

We didn't change any config, so it will work with what we already have documented for gRPC, hence just added an advanced example of gRPC

### CODE REVIEW

**Comment by sredxny** [comment]
Any gramatical/semantic correction is appreciated!

**Review by marksou — APPROVED** [review]
👍

**Review by gregdelhon — COMMENTED** [review]
Made some minor grammar improvements, otherwise this is great and ready to go!

**Comment by gregdelhon** [comment]
@matiasinsaurralde have a quick look, and then let's merge :)

**Pull request merged**
