### PR TITLE
[DX-629] TT-9622 Update tyk-pump-dashboard-config.md

### PR DESCRIPTION
**Pull request by carolwkc**
### For internal users - please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/TT-9622
---
### Preview Link

https://deploy-preview-3125--tyk-docs.netlify.app/docs/nightly/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config/#sql-example

### Description

noticed a typo in the documentation (https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config/#configuring-a-tyk-sql-aggregate-pump).  It states that the aggregate data will be stored in the tyk_analytics table rather than the tyk_aggregated table
It is:
If table_sharding is false, all the records are going to be stored in the tyk_analytics table. If set to true, daily records are stored in a tyk_analytics_YYYYMMDD date formatted table.

Should be :
If table_sharding is false, all the records are going to be stored in the tyk_aggregated table. If set to true, daily records are stored in a tyk_aggregated_YYYYMMDD date formatted table.

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
PR looks good to me Carol. Once this has been peer reviewed I will merge and release

**Review by tbuchaillot — APPROVED** [review]
Good catch!

**Pull request merged**
