### PR TITLE
[DX-123] add algolia docsearch v3

### PR DESCRIPTION
**Pull request by yurisasuke**
### **User description**
https://deploy-preview-4761--tyk-docs.netlify.app/docs/nightly

___

### **PR Type**
enhancement

___

### **Description**
- Upgraded the DocSearch library from version 2.6.3 to version 3.
- Updated the CSS and JS CDN links to point to the new version.
- Modified the DocSearch initialization configuration to comply with version 3 requirements.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>footer_scripts.html</strong><dd><code>Upgrade DocSearch library to version 3</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
<li>Updated DocSearch library from version 2.6.3 to version 3.<br> <li> Changed the CSS and JS CDN links to the new version.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4761/files#diff-d4fa06049b289a0afe0590ff7889d153196bc14542d4c22af34d9fdc40a7f5b6">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>docs-search.js</strong><dd><code>Update DocSearch initialization for version 3</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/static/js/docs-search.js
<li>Updated the DocSearch initialization configuration.<br> <li> Changed <code>inputSelector</code> to <code>container</code> as per new version requirements.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4761/files#diff-682b21a995052da72f22d76b2152b1f62445119e8563cb748ec18f1da0474c1e">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
PR LGTM @Keithwachira

Do we have [this](https://docsearch.algolia.com/docs/DocSearch-v3#performance-optimization) anywhere?

Does this PR duplicate this [PR](https://github.com/TykTechnologies/tyk-docs/pull/2245) and is [this](https://github.com/TykTechnologies/tyk-docs/blob/2407f7abe62b042157dc7c71cfa628b0f3a38f0c/tyk-docs/static/js/docs-search.js) needed?

**Comment by yurisasuke** [comment]
For later

**Pull request merged**
