### PR TITLE
[TT-12513, DX-1645, DX-1650] Draft structure for EDP templates

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1645](https://tyktech.atlassian.net/browse/DX-1645)
[DX-1650](https://tyktech.atlassian.net/browse/DX-1650)
---

New Preview Link - https://deploy-preview-5322--tyk-docs.netlify.app/docs/nightly/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/templates/

### Preview Link

[preview - template overview](https://deploy-preview-5322--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/templates/overview)
[preview - template functions](https://deploy-preview-5322--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/templates/functions)
[preview - template data](https://deploy-preview-5322--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/templates/data)
[preview - email templates](https://deploy-preview-5322--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/templates/email)

### Description

Draft structure for EDP templates

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labeled** the PR

[DX-1645]: https://tyktech.atlassian.net/browse/DX-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DX-1650]: https://tyktech.atlassian.net/browse/DX-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Added comprehensive documentation for template data structures in the Tyk Enterprise Developer Portal, covering various templates and their data.
- Introduced detailed documentation for email templates, outlining available data and example usages.
- Added a guide on global helper functions available in templates, with descriptions and examples for each function.
- Provided an overview of the template system used in the portal, explaining Golang template syntax and customization options.
- Updated the menu configuration to include new entries for the template documentation sections.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>data.md</strong><dd><code>Add comprehensive guide on template data structures</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-enterprise-developer-portal/templates/data.md

<li>Added a comprehensive guide on template data structures.<br> <li> Included detailed sections for various templates like Analytics, <br>Application Create, and Blogs.<br> <li> Provided example usages for each template.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5322/files#diff-1bf8435a09dcf1d569c7f6c66ba90353a1276f660b24bb84ce27c123f9138eb5">+771/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>email.md</strong><dd><code>Introduce detailed overview of email template data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-enterprise-developer-portal/templates/email.md

<li>Introduced a detailed overview of email template data.<br> <li> Described various email templates and their available objects.<br> <li> Included example usages for each email template.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5322/files#diff-08b824735dc8fdea52c3c0b08951870f587aea4526ee763fe961883c66440380">+377/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>functions.md</strong><dd><code>Add guide on global helper functions for templates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-enterprise-developer-portal/templates/functions.md

<li>Added a guide on global helper functions for templates.<br> <li> Listed and described various functions like CanCreateOrganisation and <br>GetCart.<br> <li> Provided example usages for each function.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5322/files#diff-8b272949556d196abdd195ea6062bdb0839531e1d42bf2e9c1535e331ca93ba3">+658/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>overview.md</strong><dd><code>Provide overview of templates in Tyk Enterprise Developer Portal</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-enterprise-developer-portal/templates/overview.md

<li>Provided an overview of templates in the Tyk Enterprise Developer <br>Portal.<br> <li> Explained the use of Golang templates for dynamic content generation.<br> <li> Linked to related documentation on template data and functions.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5322/files#diff-7a1746d1fc6f543eaae55d3f83a98ec1166aff89eb2ed9200b0fb1e093d185d2">+22/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Add menu entries for new template documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml

<li>Added new menu entries for Templates, including Overview, Email <br>Templates, Template Data, and Template Functions.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5322/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+20/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by dcs3spp** [comment]
Closing until discussion meeting has taken place to finalise structure

**Review by tbuchaillot — APPROVED** [review]

**Review by tbuchaillot — APPROVED** [review]

**Review by edsonmichaque — APPROVED** [review]
LGTM

**Review by edsonmichaque — APPROVED** [review]
LGTM

**Comment by letzya** [comment]
@MFCaballero can you please review my last commit? I improved the indentation of the HTML and go template. There was one place in which I added <p> to the text, hope it's ok

**Comment by MFCaballero** [comment]
> @MFCaballero can you please review my last commit? I improved the indentation of the HTML and go template. There was one place in which I added
> 
> to the text, hope it's ok

perfect! Thank you so much

**Review by MFCaballero — APPROVED** [review]
thanks

**Pull request merged**
