### PR TITLE
[DX-592]only show h2 and h3 on right nav

### PR DESCRIPTION
**Pull request by yurisasuke**
### For internal users - please add a Jira DX PR ticket to the subject!
DX-592
### Preview Link
Before removing h4 : https://tyk.io/docs/configure/outbound-email-configuration/
After removing h4 : https://deploy-preview-3104--tyk-docs.netlify.app/docs/nightly/configure/outbound-email-configuration/

### CODE REVIEW

**Comment by dcs3spp** [comment]
@keith can you add a preview link with a page for testing so that I can review

**Comment by yurisasuke** [comment]
> @keith can you add a preview link with a page for testing so that I can review

@dcs3spp  I have added the links (2 of them one to show the output before this change and one to show the result after this change)

**Review by dcs3spp — APPROVED** [review]
nice! lgtm

**Pull request merged**
