### PR TITLE
[Dx 786]: Plugins Getting Started Tabs - Refactor To Fix Right Nav Menu Display

### PR DESCRIPTION
**Pull request by dcs3spp**
[DX-786](https://tyktech.atlassian.net/browse/DX-786)

[preview](https://deploy-preview-3576--tyk-docs.netlify.app/docs/nightly/plugins/get-started-plugins/)

Fix duplicate right nav bar menu items in[ plugins getting started](https://tyk.io/docs/plugins/get-started-plugins), introduced by the Tyk OSS & Tyk Self-Managed tabs.

Clarification: the tabs we use in markdown `{{< tabs_start >}}` do not play well with the right side navigation and causing confusion from UX perspective

This PR refactors the[ Getting Started](https://tyk.io/docs/plugins/get-started-plugins/) page for Go plugins into 2 separate pages for Self-Managed & OSS.

[DX-786]: https://tyktech.atlassian.net/browse/DX-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dcs3spp** [comment]
@letzya This is the plugins PR we discussed this morning relating to the refactored plugins Quickstart to remove tab

**Review by rewsmith — APPROVED** [review]
LGTM

**Comment by dcs3spp** [comment]
> LGTM

Thanks @rewsmith I have merged and released

**Pull request merged**
