### PR TITLE
[TT-3390] Add new use_param and param_name to signaure validation

### PR DESCRIPTION
**Pull request by furkansenharputlu**
`v3.0.8`, `v4.0.1`

### CODE REVIEW

**Comment by marksou** [comment]
Hi @furkansenharputlu do we need to hold off merging until v4 release?

**Comment by furkansenharputlu** [comment]
I am not sure how the documentation PRs are handled for releases but this one should go out with `release-4.0.1` and `release-3.0.8` not with `release-4.0.0`

**Comment by buger** [comment]
We can merge to master now, AND during preparing release, do not forget merge to release branches.

**Comment by buger** [comment]
@ilijabojanovic btw, probably make sense ensure that final QA regression testing checklist include docs check.

**Comment by furkansenharputlu** [comment]
@buger @marksou Can you please approve if you are ok? Btw, I think `release-3-lts` branch is already ready and we can merge there, right? However, why don't a branch exist for `release-4`?

**Review by marksou — APPROVED** [review]
LGTM

**Comment by agata-wit** [comment]
@buger @marksou is there any update on what @furkansenharputlu asked about release-4 docs?

**Comment by marksou** [comment]
@agata-wit @furkansenharputlu I don't think there's a specific reason why we haven't created a v4 branch yet. We do need to understand how best to remember to push this when v4.0.1 is released. @buger what is our best way of flagging this for that release if we merge to master now (and v3 release versions)? If everyone is happy I'll create a `release-4.0` branch

**Comment by agata-wit** [comment]
@marksou please create then. We'll merge and close then.

**Comment by marksou** [comment]
@agata-wit @furkansenharputlu @buger I have now created a `release-4.0` branch.

**Comment by furkansenharputlu** [comment]
@marksou This feature is not for `release-4.0`, it is for `release-4.0.1` so I think we should create `release-4` branch. 

cc: @buger

**Comment by letzya** [comment]
@furkansenharputlu please check if we need this pr https://github.com/TykTechnologies/tyk-docs/pull/1772/files

**Comment by letzya** [comment]
@furkansenharputlu

**Comment by letzya** [comment]
@furkansenharputlu

**Comment by furkansenharputlu** [comment]
@yaara yes we need it.

**Comment by letzya** [comment]
out of date. Reopened the TT-3390 ticket

**Pull request closed without merging**
