### PR TITLE
[DX-1661 DX-1663] Update stable branch updater for 5.6 release

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1661](https://tyktech.atlassian.net/browse/DX-1661)
[DX-1663](https://tyktech.atlassian.net/browse/DX-1663)
---

### Preview Link

<br>

### Description

Update stable branch updater for 5.6 release

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

[DX-1661]: https://tyktech.atlassian.net/browse/DX-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DX-1663]: https://tyktech.atlassian.net/browse/DX-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
configuration changes

___

### **Description**
- Updated the GitHub Actions workflow to support the new `release-5.6` branch.
- Changed the branch name in the workflow configuration to ensure it triggers correctly for the 5.6 release.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>stable-updater.yaml</strong><dd><code>Update stable branch updater for 5.6 release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.github/workflows/stable-updater.yaml

<li>Updated the branch name from <code>release-5.5</code> to <code>release-5.6</code>.<br> <li> Modified the condition to check for <code>refs/heads/release-5.6</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5377/files#diff-f7fcfa8300d37bebb207c3b4355f4361cd5c0cbf353e5dff62a50777179ee38d">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by dcs3spp** [comment]
closing PR to make queue easier to maintain

**Review by sharadregoti — APPROVED** [review]

**Pull request merged**
