### PR TITLE
[DX-501]remove directories with one page

### PR DESCRIPTION
**Pull request by yurisasuke**
### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link
https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/getting-started/quick-start/

### Description
- Directory with single page should be converted into pages.

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by dcs3spp — COMMENTED** [review]
Hi @Keithwachira, PR looks good, maybe double check the following:

Deployment and Operations

Tyk Cloud has two pages in overview section. I think we need 1 page here that is set as an overview page
https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/tyk-cloud/ 

Licensing & deployment models has one page https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/tyk-on-premises/licensing/

Single sign on
https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/advanced-configuration/integrate/sso/

Setup infrastructure and monitoring
https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/planning-for-production/monitoring/

Monitor Tyk Components & Their Dependencies
https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/planning-for-production/monitoring/tyk-components/

**Comment by yurisasuke** [comment]
> Hi @Keithwachira, PR looks good, maybe double check the following:
> 
> Deployment and Operations
> 
> Tyk Cloud has two pages in overview section. I think we need 1 page here that is set as an overview page https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/tyk-cloud/
> 
> Licensing & deployment models has one page https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/tyk-on-premises/licensing/
> 
> Single sign on https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/advanced-configuration/integrate/sso/
> 
> Setup infrastructure and monitoring https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/planning-for-production/monitoring/
> 
> Monitor Tyk Components & Their Dependencies https://deploy-preview-2956--tyk-docs.netlify.app/docs/nightly/planning-for-production/monitoring/tyk-components/

It is still in draft i haven't finished it yet.

**Comment by yurisasuke** [comment]
replaced b y https://github.com/TykTechnologies/tyk-docs/pull/2957

**Comment by yurisasuke** [comment]
replaced by https://github.com/TykTechnologies/tyk-docs/pull/2957

**Pull request closed without merging**
