### PR TITLE
set grpc load balancing as not supported feature

### PR DESCRIPTION
**Pull request by sredxny**
gRPC load balacing is not working, we need to reflect that in the documentation

### CODE REVIEW

**Review by marksou — APPROVED** [review]
👍

**Comment by marksou** [comment]
@sredxny can you remind me which release this is for?

**Comment by sredxny** [comment]
@marksou this is a cúrrent issue, bsically is let the people know that this doesnt work

**Comment by marksou** [comment]
@sredxny are you happy for me to merge?

**Pull request merged**
