### PR TITLE
draft for complexity limiting and field restriction

### PR DESCRIPTION
**Pull request by pvormste**

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]
I reviewed technically, it is very clear doc!

**Comment by furkansenharputlu** [comment]
@pvormste wouldn't it be good to talk about user can set query depth limiting and field base permissions by using `key`s? At the beginning of the description of the features.

**Review by marksou — COMMENTED** [review]
👍

**Comment by pvormste** [comment]
I added Furkan's proposed changes @marksou

**Review by marksou — APPROVED** [review]
👍

**Pull request merged**
