### PR TITLE
Draft for Hybrid on AWS installation

### PR DESCRIPTION
**Pull request by excieve**
This will be linked directly from AWS Marketplace product page but also available from the docs menu on Hybrid. This is draft because there's no public listing yet. Link to the product page might be also added later.

### CODE REVIEW

**Comment by excieve** [comment]
@marksou Let's collaborate if this needs improvements.

**Comment by excieve** [comment]
@james-tyk FYI

**Review by marksou — APPROVED** [review]
Looks good. We can hide the page from the menu if you want before it's listed on AWS Marketplace?

**Comment by excieve** [comment]
@marksou I'd rather this doesn't get indexed by search engines as a docs page before we launch. And there will probably be some more related docs added. So maybe let's leave it as a draft for now? AFAIK Hugo doesn't publish drafts by default.

**Comment by marksou** [comment]
@excieve Yes, that's correct.

**Pull request merged**
