### PR TITLE
Update tyk-sync.md

### PR DESCRIPTION
**Pull request by carolwkc**
Remove Go installation option

### For internal users - please add a Jira DX PR ticket to the subject!
---
## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]

**Review by dcs3spp — DISMISSED** [review]
If Go v1.19 is now the minimum version required, is this a breaking change for some customers? Is there a need to link to an upgrade guide?

**Comment by caroltyk** [comment]
> If Go v1.19 is now the minimum version required, is this a breaking change for some customers? Is there a need to link to an upgrade guide?

**Comment by letzya** [comment]
@caroltyk why do we need the message about the go version? It's from the time users had to compile the code but now we provide docker image. Can we maybe remove it and add it to GH if it's not there already ? We have a link to GH so it won't be an issue

**Comment by carolwkc** [comment]
> @caroltyk why do we need the message about the go version? It's from the time users had to compile the code but now we provide docker image. Can we maybe remove it and add it to GH if it's not there already ? We have a link to GH so it won't be an issue

I'm ok  to remove this part and only offer Docker / Package Cloud as installation options.

**Comment by carolwkc** [comment]
@dcs3spp for review, thanks

**Pull request merged**
