### PR TITLE
[DX-1203, TT-11115] Added default values for min/max TLS version

### PR DESCRIPTION
**Pull request by andyo-tyk**
### Description
Added default values for min/max TLS version

___

## **Type**
documentation

___

## **Description**
- Updated the TLS and SSL documentation to include information on setting both minimum and maximum TLS versions.
- Introduced default values for TLS `min_version` and `max_version`, enhancing clarity for users on the default behavior.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tls-and-ssl.md</strong><dd><code>Documentation Update for TLS Version Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
<li>Expanded the TLS version configuration section to include <code>max_version</code>.<br> <li> Added default values for <code>min_version</code> and <code>max_version</code> if not <br>configured.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4303/files#diff-b17c249d7eeec9b4df7b3d5b3a59081c026f529f5e0888153443cd2f72e2d97c">+8/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
PR LGTM
@andyo-tyk Is this PR intended for current and historic releases?

**Comment by andyo-tyk** [comment]
Yes, I don't know how far back it needs to go - so it could probably just go in current/latest version.

**Pull request merged**
