### PR TITLE
Fix Tyk Cloud Signup link

### PR DESCRIPTION
**Pull request by mitjaziv**
## Description

```
Change fixes Tyk Cloud signup link.
```
## Screenshots (if appropriate)
https://deploy-preview-2652--tyk-docs.netlify.app/docs/nightly/tyk-cloud/getting-started-tyk-cloud/create-account/

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [x] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I have added a preview link.

### CODE REVIEW

**Comment by mitjaziv** [comment]
@letzya @Keithwachira This will need to be deployed in production webpage, when it's merged.

**Review by dcs3spp — APPROVED** [review]
lgtm Mitja

**Comment by mitjaziv** [comment]
I am still waiting for confirmation of the second URL, before merging.

**Comment by dcs3spp** [comment]
@mitja have you had confirmation of the second URL yet?

**Comment by letzya** [comment]
@mitjaziv can we merge or close please?

**Comment by letzya** [comment]
It has conflicts. Since we are releasing the new website and also since it's an old draft I'm closing it. Feel free to reopen it when it's relevant again

**Pull request closed without merging**
