### PR TITLE
Docs for KV system

### LINKED ISSUE #1229: 2.10 KV Store for Sercrets in Configuration

### PR DESCRIPTION
**Pull request by adelowo**
- [x] Add KV store page
- [x] Add config options to https://tyk.io/docs/configure/tyk-gateway-configuration-options/

Fixes https://github.com/TykTechnologies/tyk-docs/issues/1229

### CODE REVIEW

**Comment by marksou** [comment]
Hi @adelowo, the `config` section is now `tyk-configuration-reference`. Can you resolve the merge conflict for the 2 pages?

**Comment by adelowo** [comment]
Sure. Will do that

**Review by marksou — APPROVED** [review]
Looks ok, apart from the merge conflicts

**Comment by adelowo** [comment]
Will sort merge conflicts tomorrow @marksou

**Comment by buger** [comment]
@adelowo we need to add docs on at which part of Tyk KV store can be used

**Comment by adelowo** [comment]
@buger PTAL https://github.com/TykTechnologies/tyk-docs/pull/1002/files#diff-6f0f408379b71ecc0cdd2b775af21c41R20-R25

@marksou fixed merge conflicts

**Comment by marksou** [comment]
Merge as part of 2.10

**Review by marksou — APPROVED** [review]
👍

**Pull request merged**
