### PR TITLE
Proposed typos and formatting fixes in API Definition doc

### PR DESCRIPTION
**Pull request by cvillerm**

### CODE REVIEW

**Comment by mvdan** [comment]
This looks good, thanks! Although I want @marksou's input regarding the american vs british spellings.

**Comment by cvillerm** [comment]
Note that I kept british spelling, except when this was referring (already elsewhere) to something like an american-spelled header name

**Comment by cvillerm** [comment]
Actually, when I changed "authorization code" to "authorisation" code, this was to keep the documentation consistent as there were other references to "authorisation code" elsewhere in the doc.

**Comment by marksou** [comment]
@mvdan @cvillerm All looks good to me

**Comment by mvdan** [comment]
Thanks again @cvillerm!

**Pull request merged**
