### PR TITLE
[TT-1501] Add Portal set up links

### PR DESCRIPTION
**Pull request by marksou**

### CODE REVIEW

**Review by rewsmith — CHANGES_REQUESTED** [review]
Hi Mark.  I'm guessing it's not possible to link to the Self-Managed Dev Portal Tutorial tab??  If not possible then I think we should explicitly state in the link to follow the Self-Managed instructions.

**Comment by marksou** [comment]
Hi @rewsmith you are correct. I'll add something about the self-managed tab.

**Review by rewsmith — APPROVED** [review]

**Pull request merged**
