### PR TITLE
[DX-851] MDCB 2.4.1 release notes

### PR DESCRIPTION
**Pull request by carolwkc**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>
Add MDCB 2.4.1 release notes for https://github.com/TykTechnologies/tyk-sink/releases/tag/v2.4.1

---

### Preview Link

<br>

[preview](https://deploy-preview-3645--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4/)

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

### CODE REVIEW

**Review by sredxny — APPROVED** [review]
🚀

**Review by dcs3spp — COMMENTED** [review]
Hi @caroltyk for MDCB release notes can we update to use new template?

**Comment by carolwkc** [comment]
@dcs3spp updated with the RN template

**Review by dcs3spp — CHANGES_REQUESTED** [review]
Hi @caroltyk I have updated the release note with headings from the [release notes guide](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes) and [template](https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-5.2/). Would you be able to verify the changes I have made make sense for MDCB?

Does MDCB have docker images? If so could add link to docker images for each 2.4.x release? 

I think we can then merge and release after above confirmed and this will then give a template for future MDCB releases

**Comment by carolwkc** [comment]
Thanks @dcs3spp . Docker image links added. Please merge and release, thanks!

**Pull request merged**
