### PR TITLE
[DX-1313] Mobile docs new homepage

### PR DESCRIPTION
**Pull request by fredoyetayo**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

https://deploy-preview-4705--tyk-docs.netlify.app/docs/nightly/ 
<br>

### Description
`
New Tyk Docs homepage design for mobile. This implementation makes the mobile more responsive and gives a different view for the user if browsing from mobile devices. 
<br>

#### Screenshots (if appropriate)
<br>
Screenshot 2024-05-31 at 11 47 03[Screenshot 2024-05-31 at 11 47 03](https://github.com/TykTechnologies/tyk-docs/assets/29312441/ebd05697-18c9-4674-8e87-e37de4ede7d4)

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

### **PR Type**
Enhancement, Documentation

___

### **Description**
- Added and adjusted styles in `home.scss` to support a new mobile homepage view, including hiding desktop elements and adjusting padding and font sizes for mobile elements.
- Introduced new sections in `index.html` for mobile users, including a mobile banner, a "Learn about Tyk API management" section, and a "Browse by Product" section.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>home.scss</strong><dd><code>Added and adjusted styles for mobile homepage view.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/home.scss
<li>Added new styles for mobile view, including <code>.mobile-banner</code>, <br><code>.container-mobile</code>, and <code>.mobile-home-section</code>.<br> <li> Hid desktop elements in mobile view.<br> <li> Adjusted padding and font sizes for mobile elements.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4705/files#diff-e16aedadc92e87ceb758b51289e947ab745c970390648880519c540e3b30e722">+104/-0</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.html</strong><dd><code>Added new mobile-specific sections to homepage layout.</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/themes/tykio/layouts/index.html
<li>Added a new mobile banner section.<br> <li> Introduced a "Learn about Tyk API management" section for mobile.<br> <li> Added a "Browse by Product" section for mobile.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4705/files#diff-052b986feaae91359c4f00ee6bd86b62595c20d895039fe4feaca7ab00e644d9">+131/-0</a>&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by yurisasuke** [comment]
@fredoyetayo  The new search widget does not have the search functionality.
Screenshot 2024-06-03 at 05 36 22

**Comment by yurisasuke** [comment]
@fredoyetayo Also is it okay that we now have two search widget on the homepage ? Would it be better for us to remove the one on the toolbar in the homepage and for it to only be available in the other pages apart from homepage? What do you think ?
Screenshot 2024-06-03 at 05 33 57
hat do you think ?

**Comment by letzya** [comment]
@ArturoSerrano changed to draft till you decide what to do with this PR. Thanks

**Comment by letzya** [comment]
@Keithwachira is it worth merging this? is it improving anything? if not let's close it for now. The jira remains open

**Comment by yurisasuke** [comment]
> @Keithwachira is it worth merging this? is it improving anything? if not let's close it for now. The jira remains open

@letzya No Fred did not complete working on it.I let two comments on the pr 2 weeks ago

**Comment by letzya** [comment]
Closing it for now @Arturas-Salivonas can open it from jira if he wants to

**Pull request closed without merging**
