### PR TITLE
[DX-1344] Replace whitelist/blacklist content where possible, for tier 1 compliance with inclusive naming

### PR DESCRIPTION
**Pull request by dcs3spp**
### For internal users - Please add a Jira DX PR ticket to the subject!

[DX-1344](https://tyktech.atlassian.net/browse/DX-1344)
---

### Preview Link

<br>

### Description

Within the docs content there are occurrences of whitelist/blacklist. This ticket involves updating the content where possible. Due to 3rd party dependencies and configuration parameters in Tyk components, it will not be possible to update some content until the product has been updated.

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

[DX-1344]: https://tyktech.atlassian.net/browse/DX-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
enhancement, documentation

___

### **Description**
- Updated terminology across various documentation files to use more inclusive language.
- Changed terms like "white_list" and "black_list" to "allow_list" and "block_list".
- Modified "white label" to "customise the portal's branding" in developer portal options.
- Ensured consistency in terminology updates across all modified files.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>custom-developer-portal-options.md</strong><dd><code>Update Inclusive Language in Developer Portal Options</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
<li>Updated terminology from "white label" to "customise the portal's <br>branding".<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4640/files#diff-2013bfe0785c0e5392521c67d4bef85eeb681e12b432d184dcb9a9d0c85ca33c">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>import-apis.md</strong><dd><code>Update Terminology in API Import Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/getting-started/import-apis.md
<li>Changed "White Lists" to "Allow Lists" and "black-list" to <br>"block-list" in API import documentation.<br> <li> Updated terminology in API mocking section.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4640/files#diff-34a50aae8b2c487ae7fc201468a8d63f590fffa034656fdc262c1ffb37c0a894">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>versioning.md</strong><dd><code>Update Inclusive Language in API Versioning Concepts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/getting-started/key-concepts/versioning.md
<li>Updated terminology from "white_list" and "black_list" to "allow_list" <br>and "block_list".<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4640/files#diff-5f5d913588858b56d4c0e81bafaf8fb30e4ef7ae663f830509dfae2d40a7c05c">+5/-5</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>version-2.4.md</strong><dd><code>Update Inclusive Language in Tyk Dashboard Release Notes</code>&nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.4.md
- Updated terminology in Mutual TLS and Swagger API import sections.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4640/files#diff-214dc344307076d76617042f2b87a6f2151392ac300bb45d4b725acb6050c13f">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>version-2.4.md</strong><dd><code>Update Inclusive Language in Tyk Gateway Release Notes</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.4.md
- Updated terminology in Mutual TLS and Swagger API import sections.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4640/files#diff-9f9c91c54d032e3614315c4cbaebd95d26e24842e33015f9f84525034ca13ae6">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>api-def-version.md</strong><dd><code>Update Inclusive Language in API Definition Versioning</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/shared/api-def-version.md
<li>Updated terminology from "white_list" and "black_list" to "allow_list" <br>and "block_list".<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4640/files#diff-61c7f2f742e5ac59fad7658e8f0eb94c08ddfce105cc1e790c22fcb25d03c626">+9/-9</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by slega — APPROVED** [review]
I don't see any issues regarding the portal

**Review by andyo-tyk — APPROVED** [review]
Changes look good to me, thanks.

**Pull request merged**
