### PR TITLE
First draft of ingress controller doc

### PR DESCRIPTION
**Pull request by marksou**
Note that I had to change the Annotations table to a list as the JSON object example broke our table format, and couldn't be viewed properly. Something to discuss on Friday.

### CODE REVIEW

**Review by joshblakeley — APPROVED** [review]
I have added to the installation section and fixed a bunch of typos.

Would be good to bully one more reviewer before merge - preferably getting them to try the installation.

I'll throw it out to the CE team

**Comment by asoorm** [comment]
I would break up this document a bit into several pages - something like the following structure:

```
- Kubernetes (Intro/Concepts/Overview)
  - Installation
    - Tyk CE
      - Ingress Controller
    - Tyk Pro
      - Ingress Controller
      - Service Mesh Controller
  - Usage
```

or 

```
- Ingress Controller
  - Installation
    - Tyk CE
    - Tyk Pro
  - Usage
- Service Mesh
  - Installation
    - Tyk CE
    - Tyk Pro
  - Usage
```

---

Kubernetes - Intro/Concepts/Overview 
(can also be broken down into Ingress Controller / Service Mesh sections)

Ingress
- What is an Ingress Controller
- Why use Tyk?

Mesh
- What is a Service Mesh?
- Why use Tyk?

Core Features

- Security
- Routing
- GUI
- Tracing / Monitoring / Logging

Architecture

- Ingress Deployment vs ReplicaSet
- Diagrams for ingress
- Diagrams for Mesh

Further detail can be fleshed out without making one massive document with stuff in the wrong order.

**Comment by marksou** [comment]
@asoorm I prefer your second approach. I'll start work on it.

**Comment by marksou** [comment]
@asoorm @excieve  For the "What is an Ingress Controller"  we can just link to Kubernetes Docs. For example:
https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress
For "What is a Service Mesh" Could we link to this? https://www.nginx.com/blog/what-is-a-service-mesh/

**Pull request merged**
