### PR TITLE
[DX-1161] Update Dashboard API User Group samples

### PR DESCRIPTION
**Pull request by rewsmith**
## **User description**
---

### Description
The samples we provide in the docs for Dashboard User Groups are wrong and need to be updated.

All references to `/api/user_groups` should be replaced with `/api/usergroups`.

Additionally, the List User Groups sample response is incorrect.  `user_groups` should read `groups`
<br>

___

## **Type**
documentation

___

## **Description**
- Corrected API endpoint paths in the documentation from `/api/user_groups` to `/api/usergroups`.
- Updated sample responses to reflect the correct response object key (`groups` instead of `user_groups`) and included the `active` field.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>user-groups.md</strong><dd><code>Update Dashboard API User Group Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/tyk-apis/tyk-dashboard-api/user-groups.md
<li>Updated API endpoint paths from <code>/api/user_groups</code> to <code>/api/usergroups</code>.<br> <li> Changed the response object key from <code>user_groups</code> to <code>groups</code> in the <br>sample responses.<br> <li> Added <code>active</code> field to the sample responses for user groups.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4231/files#diff-d05215f310dacc51d444ca4f2bac6135d68be32bdb20519930fe08e757486ad4">+10/-7</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by dcs3spp — COMMENTED** [review]
@rewsmith Thanks for submitting bug fix!! Should the PUT and DELETE endpoint paths be `api/usergroups` also? Once confirmed with peer review by @andyo-tyk I will approve merge and release

**Review by andyo-tyk — APPROVED** [review]
Looks good to me.

**Comment by rewsmith** [comment]
@andyo-tyk Just spotted something else.
The Delete User Group Resource URL is (presumably) wrong.  It's currently `/api/users/{user-id}` but I presume should be `/api/usergroups/{user_group-id}`

**Comment by dcs3spp** [comment]
> @andyo-tyk Just spotted something else. The Delete User Group Resource URL is (presumably) wrong. It's currently `/api/users/{user-id}` but I presume should be `/api/usergroups/{user_group-id}`

@andyo-tyk @rewsmith Similar spot with the PUT User Group endpoint, sample mismatches the PUT user group Resource URL

**Comment by rewsmith** [comment]
> > @andyo-tyk Just spotted something else. The Delete User Group Resource URL is (presumably) wrong. It's currently `/api/users/{user-id}` but I presume should be `/api/usergroups/{user_group-id}`
> 
> @andyo-tyk @rewsmith Similar spot with the PUT User Group endpoint, sample mismatches the PUT user group Resource URL

Just made further updates.  Can you check again @andyo-tyk

**Pull request merged**
