### PR TITLE
saas_upgrade_guide v1

### PR DESCRIPTION
**Pull request by nerdydread**
### For internal users - Please add a Jira DX PR ticket to the subject!
DX-1047

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ x] I **labelled** the PR

### CODE REVIEW

**Comment by dcs3spp** [comment]
@nerdydread You should be able to pull down the changes from the parent branch that fixes the CI error. Can you raise a Jira ticket within the DX space for review and add the ticket ID in the PR header?

**Comment by dcs3spp** [comment]
@nerdydread Can this PR now be closed?

**Review by Fadzli-fast — COMMENTED** [review]
Looks good to me

**Comment by dcs3spp** [comment]
Closing PR, structure has been updated in parent branch dx-1047

**Pull request closed without merging**
