### PR TITLE
Fix swagger.yml inconsistencies

### PR DESCRIPTION
**Pull request by jeffy-mathew**
- Update gateway version to 3.2.0
 - Add policy capabilities from GW swagger
 - Enclose API paths in '' which were not before
 - Fix intendation for /tyk/oauth/clients/{apiID}, remove redundant PUT /tyk/oauth/clients/{apiID}
 - Remove malformed special characters with ' for don't
 - Add cache_response_codes component

### CODE REVIEW

**Review by marksou — APPROVED** [review]
Looks good to me 👍

**Review by vaske — APPROVED** [review]

**Comment by marksou** [comment]
@jeffy-mathew Shall we close this now as we are now synced to the tyk repo?

**Comment by jeffy-mathew** [comment]
@marksou Yes, we can close this

**Comment by marksou** [comment]
Closing this as fixed here - https://github.com/TykTechnologies/tyk-docs/commit/41a1465c80d0e31b00ff9d0aefe219ccd18de47a

**Pull request closed without merging**
