### PR TITLE
[DX-1057] Mobile UI Fixes for TYK Docs - Jira DX PR Ticket: 

### PR DESCRIPTION
**Pull request by fredoyetayo**
## **User description**
# Mobile UI Fixes for TYK Docs - Jira DX PR Ticket: DX-1057
Preview Link -  https://deploy-preview-4184--tyk-docs.netlify.app/docs/nightly/

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link
https://deploy-preview-4184--tyk-docs.netlify.app/docs/nightly/
<br>

### Description
I have made several enhancements to the mobile navigation UI, addressing issues related to responsiveness, navigation, and common bugs. The changes include adjustments for header navigation, menu, sizing, page width, and responsiveness issues on mobile and tablet devices.

**Mobile Navigation/Menu Bar** - Made the mobile menu bar full width and removed the secondary burger menu close button. I also properly aligned the navigation content to maintain equal padding. The mobile menu was also made 100% responsive across any device (tablet/mobile). Also changes were made to the table of content container to make it more responsive. - please check below for screenshots

**Mobile width** - previously the mobile docs website was not well aligned with some contents not maintaining a right side padding. I made changes to ensure that all contents now fall within the right container and also maintain equal padding to guarantee 100% responsiveness.  - - please check below for screenshots

<br>

#### Screenshots (if appropriate)
Screenshot 2024-02-29 at 15 21 45
Screenshot 2024-02-29 at 15 21 56
Screenshot 2024-02-29 at 15 22 31

<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

## **Type**
enhancement

___

## **Description**
- Introduced enhancements to mobile navigation UI, including adjustments for header navigation, menu sizing, and responsiveness.
- Improved button appearance and alignment across the site.
- Adjusted content and sidebar spacing for a better mobile viewing experience.
- Made structural adjustments to HTML for consistency and better usability.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>_header.scss</strong><dd><code>Enhancements to Header Navigation and Button Styles</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_header.scss
<li>Added styles for <code>.button-cta</code> to improve button appearance.<br> <li> Adjusted padding for <code>.header__tabs-menu</code> for better spacing.<br> <li> Changed navigation display to column in <code>.header__tabs-menu</code>.<br> <li> Modified hover and active states width in <code>.header__tabs-menu</code>.<br> <li> Commented out a fixed position top value for <code>.burger</code>.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-bf4eda8fafa3865fc39706d1697f921b954c1b270ba54571c12118f1c3cc8ac5">+15/-3</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_print.scss</strong><dd><code>Print View Alignment Improvement</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_print.scss
<li>Added a right property to <code>.hasSidebar .page-content</code> for better <br>alignment in print view.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-8c4b39ad5a7f93bb6b40e5306a1aa4451816d4e7bda434119e3c0397c6bc4983">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_side-menu.scss</strong><dd><code>Mobile Side Menu UI Enhancements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_side-menu.scss
<li>Adjusted padding and width for <code>.page-submenu</code> for improved mobile view.<br> <li> Added padding to <code>.menu_top-cta</code>.<br> <li> Disabled display for <code>.submenu-close</code> to improve usability.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-ec2a82dc0661a7f9d0f574a4b599afbe4ff53f179b52e683311c41643b6aed72">+9/-5</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_structure.scss</strong><dd><code>Content Spacing Improvement in Mobile View</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_structure.scss
<li>Added padding-right to <code>.hasSidebar .page-content</code> for better content <br>spacing.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-9351f90fa51c1ad933900122d614f50cee937500d4e7ed8a7b4b6ce1f49d3bd3">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_table-of-contents.scss</strong><dd><code>Table of Contents Mobile View Enhancements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_table-of-contents.scss
<li>Adjusted positioning and background for better visibility in mobile <br>view.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-a9b2fe01555dddb1b7c553a79ac798f880b16abd38256b3ed7d741a50c4342ae">+9/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_ui.scss</strong><dd><code>UI Button Alignment Enhancement</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/assets/scss/_ui.scss
<li>Added margin-left to <code>.button.button-secondary</code> for better alignment.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-5f5c47d79bfaaf0883fa0dceae2dcc5ba4c81bbf17bfd9b4e745177fa9240917">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>side_menu.html</strong><dd><code>Side Menu HTML Structure Adjustment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/themes/tykio/layouts/partials/side_menu.html
<li>Modified class name for div wrapping <code>menu_top_ctas</code> partial for <br>consistency.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4184/files#diff-011c72b069ea805e45225774a840dc386c662e6b006aa1c732065933fd8d253b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by letzya** [comment]
@fredoyetayo could you please share in the description how and what have you tested?

**Comment by fredoyetayo** [comment]
> @fredoyetayo could you please share in the description how and what have you tested?

@letzya Thank you Yaara. I've added extra comments to the description and also attached screenshots.

**Comment by yurisasuke** [comment]
Screenshot 2024-03-01 at 15 41 46
@fredoyetayo  is there a way to make the burger menu move app together with the toolbar ? The toolbar moves up and leaves the burger menu down.

**Comment by fredoyetayo** [comment]
> Screenshot 2024-03-01 at 15 41 46 @fredoyetayo is there a way to make the burger menu move app together with the toolbar ? The toolbar moves up and leaves the burger menu down.

Hi @Keithwachira I've made another commit. Kindly check.

**Review by yurisasuke — APPROVED** [review]

**Pull request merged**
